// This file is auto-generated by @hey-api/openapi-ts

import { type Client, type ClientMeta, formDataBodySerializer, type Options as Options2, type RequestResult, type TDataShape } from './client';
import { client } from './client.gen';
import type { CancelDocumentJobData, CancelDocumentJobErrors, CancelDocumentJobResponses, ClassifyDocumentsData, ClassifyDocumentsErrors, ClassifyDocumentsResponses, CreatePortalMagicLinkData, CreatePortalMagicLinkErrors, CreatePortalMagicLinkResponses, CropDocumentData, CropDocumentErrors, CropDocumentResponses, DownloadArtifactData, DownloadArtifactErrors, DownloadArtifactResponses, ExtractDocumentData, ExtractDocumentErrors, ExtractDocumentResponses, FaceMatchDocumentData, FaceMatchDocumentErrors, FaceMatchDocumentResponses, GetDocumentJobData, GetDocumentJobErrors, GetDocumentJobResponses, ListDocumentJobsData, ListDocumentJobsErrors, ListDocumentJobsResponses, ListPortalChannelsData, ListPortalChannelsErrors, ListPortalChannelsResponses, ListPortalFormsData, ListPortalFormsErrors, ListPortalFormsResponses, SplitDocumentData, SplitDocumentErrors, SplitDocumentResponses, SubmitDocumentJobData, SubmitDocumentJobErrors, SubmitDocumentJobResponses, UploadArtifactData, UploadArtifactErrors, UploadArtifactResponses, ZeroShotDocumentData, ZeroShotDocumentErrors, ZeroShotDocumentResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Extract structured fields from a document
 *
 * Extracts structured fields from a single document using the templates
 * configured for your tenant. The platform selects the best template for the
 * uploaded document.
 *
 */
export const extractDocument = <ThrowOnError extends boolean = false>(options: Options<ExtractDocumentData, ThrowOnError>): RequestResult<ExtractDocumentResponses, ExtractDocumentErrors, ThrowOnError> => (options.client ?? client).post<ExtractDocumentResponses, ExtractDocumentErrors, ThrowOnError>({
    ...formDataBodySerializer,
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/Document/extraction',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * Classify one or more documents
 *
 * Detects the document type against the classes configured for your tenant.
 * Repeat the `files` field to classify several documents in one call.
 *
 */
export const classifyDocuments = <ThrowOnError extends boolean = false>(options: Options<ClassifyDocumentsData, ThrowOnError>): RequestResult<ClassifyDocumentsResponses, ClassifyDocumentsErrors, ThrowOnError> => (options.client ?? client).post<ClassifyDocumentsResponses, ClassifyDocumentsErrors, ThrowOnError>({
    ...formDataBodySerializer,
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/Document/classifier',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * Discover fields without a template
 *
 * Reports the fields the model can find in a document you have no template
 * for, each with a confidence score from `0` to `100`.
 *
 */
export const zeroShotDocument = <ThrowOnError extends boolean = false>(options: Options<ZeroShotDocumentData, ThrowOnError>): RequestResult<ZeroShotDocumentResponses, ZeroShotDocumentErrors, ThrowOnError> => (options.client ?? client).post<ZeroShotDocumentResponses, ZeroShotDocumentErrors, ThrowOnError>({
    ...formDataBodySerializer,
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/Document/zero-shot',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * Crop pages to the document
 *
 * Trims pages down to the document itself — useful when the source is a photo
 * or a scan with a border, a desk or a second page in frame.
 *
 */
export const cropDocument = <ThrowOnError extends boolean = false>(options: Options<CropDocumentData, ThrowOnError>): RequestResult<CropDocumentResponses, CropDocumentErrors, ThrowOnError> => (options.client ?? client).post<CropDocumentResponses, CropDocumentErrors, ThrowOnError>({
    ...formDataBodySerializer,
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/Document/crop',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * Split a bundle into its documents
 *
 * Breaks one file into the documents it contains, returning a detected type and
 * page range per segment. Accepts files up to 500 MB — well above the 10 MB
 * limit that applies to the other document endpoints. PDFs work best; other
 * supported formats are accepted but usually return a single segment.
 *
 */
export const splitDocument = <ThrowOnError extends boolean = false>(options: Options<SplitDocumentData, ThrowOnError>): RequestResult<SplitDocumentResponses, SplitDocumentErrors, ThrowOnError> => (options.client ?? client).post<SplitDocumentResponses, SplitDocumentErrors, ThrowOnError>({
    ...formDataBodySerializer,
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/Document/split',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * Match a selfie against identity documents
 */
export const faceMatchDocument = <ThrowOnError extends boolean = false>(options: Options<FaceMatchDocumentData, ThrowOnError>): RequestResult<FaceMatchDocumentResponses, FaceMatchDocumentErrors, ThrowOnError> => (options.client ?? client).post<FaceMatchDocumentResponses, FaceMatchDocumentErrors, ThrowOnError>({
    ...formDataBodySerializer,
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/Document/facematch',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * Upload the input document of an asynchronous job
 *
 * Stores a document and returns the `artifact://` reference to submit it with.
 * This is the only way to obtain one — the asynchronous job endpoints take a
 * reference, never a file.
 *
 * The document is scanned and normalized before it is stored, exactly as the
 * synchronous `/Document*` endpoints do. Images are stored as uploaded, so
 * `Crop` and `Facematch` still see the original pixels; everything else is
 * stored in its canonical form, which is what the job will read.
 *
 * The reference is reusable and expires after 7 days — see **Artifact
 * references** above.
 *
 */
export const uploadArtifact = <ThrowOnError extends boolean = false>(options: Options<UploadArtifactData, ThrowOnError>): RequestResult<UploadArtifactResponses, UploadArtifactErrors, ThrowOnError> => (options.client ?? client).post<UploadArtifactResponses, UploadArtifactErrors, ThrowOnError>({
    ...formDataBodySerializer,
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/artifacts',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * Download the bytes behind a reference
 *
 * Returns the stored bytes of an upload, or of a finished job's
 * `outputReference`. For a completed job this is the result document —
 * `application/json` for the extraction, classification and zero-shot
 * operations.
 *
 * The reference is a query parameter, not a path segment, because it is a URI
 * in its own right. Percent-encode it.
 *
 */
export const downloadArtifact = <ThrowOnError extends boolean = false>(options: Options<DownloadArtifactData, ThrowOnError>): RequestResult<DownloadArtifactResponses, DownloadArtifactErrors, ThrowOnError> => (options.client ?? client).get<DownloadArtifactResponses, DownloadArtifactErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/artifacts/content',
    ...options
});

/**
 * List document jobs
 */
export const listDocumentJobs = <ThrowOnError extends boolean = false>(options?: Options<ListDocumentJobsData, ThrowOnError>): RequestResult<ListDocumentJobsResponses, ListDocumentJobsErrors, ThrowOnError> => (options?.client ?? client).get<ListDocumentJobsResponses, ListDocumentJobsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/document-jobs',
    ...options
});

/**
 * Submit an asynchronous document job
 *
 * Queues a long-running operation. Answers `202` with a `Location` header
 * pointing at the job and a `Retry-After` hint. Poll that URL, or subscribe to
 * webhooks and let the completion event come to you.
 *
 */
export const submitDocumentJob = <ThrowOnError extends boolean = false>(options: Options<SubmitDocumentJobData, ThrowOnError>): RequestResult<SubmitDocumentJobResponses, SubmitDocumentJobErrors, ThrowOnError> => (options.client ?? client).post<SubmitDocumentJobResponses, SubmitDocumentJobErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/document-jobs',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get a document job
 */
export const getDocumentJob = <ThrowOnError extends boolean = false>(options: Options<GetDocumentJobData, ThrowOnError>): RequestResult<GetDocumentJobResponses, GetDocumentJobErrors, ThrowOnError> => (options.client ?? client).get<GetDocumentJobResponses, GetDocumentJobErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/document-jobs/{jobId}',
    ...options
});

/**
 * Cancel a document job
 */
export const cancelDocumentJob = <ThrowOnError extends boolean = false>(options: Options<CancelDocumentJobData, ThrowOnError>): RequestResult<CancelDocumentJobResponses, CancelDocumentJobErrors, ThrowOnError> => (options.client ?? client).post<CancelDocumentJobResponses, CancelDocumentJobErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/document-jobs/{jobId}/cancel',
    ...options
});

/**
 * List the forms available to the tenant
 *
 * Returns every intake form configured for your tenant, so you can resolve the
 * `formId` a magic link needs. Forms are created in the dashboard, not here.
 *
 * The response is a bare array, not the document-endpoint envelope, and it is
 * not paginated.
 *
 */
export const listPortalForms = <ThrowOnError extends boolean = false>(options?: Options<ListPortalFormsData, ThrowOnError>): RequestResult<ListPortalFormsResponses, ListPortalFormsErrors, ThrowOnError> => (options?.client ?? client).get<ListPortalFormsResponses, ListPortalFormsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/portal/forms',
    ...options
});

/**
 * List the send channels this environment can use
 *
 * The channels available for delivering a magic link. This is a property of the
 * environment — it follows the delivery credentials configured there — rather
 * than a per-tenant or per-plan entitlement, so it may be shorter than expected.
 *
 * WhatsApp additionally requires a Meta-approved template and respects the
 * 24-hour service window.
 *
 */
export const listPortalChannels = <ThrowOnError extends boolean = false>(options?: Options<ListPortalChannelsData, ThrowOnError>): RequestResult<ListPortalChannelsResponses, ListPortalChannelsErrors, ThrowOnError> => (options?.client ?? client).get<ListPortalChannelsResponses, ListPortalChannelsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/portal/available-channels',
    ...options
});

/**
 * Create a magic link
 *
 * Creates a link to an intake form for a named recipient and, when `sendChannel`
 * is set, dispatches it on that channel. Omit `sendChannel` to create the link
 * without sending anything and deliver it yourself.
 *
 * Send a stable `Idempotency-Key` to make retries safe: a repeat resolves to the
 * same link rather than creating a second one or charging twice.
 *
 * `url` is returned **only on the first create**. The raw token is never stored
 * in readable form, so an idempotent replay returns the same `id` with `url`
 * absent — persist it from the original `201`.
 *
 */
export const createPortalMagicLink = <ThrowOnError extends boolean = false>(options: Options<CreatePortalMagicLinkData, ThrowOnError>): RequestResult<CreatePortalMagicLinkResponses, CreatePortalMagicLinkErrors, ThrowOnError> => (options.client ?? client).post<CreatePortalMagicLinkResponses, CreatePortalMagicLinkErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/portal/magic-link',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
