// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://api-us.cogneris.ai' | 'https://api-eu.cogneris.ai' | (string & {});
};

export type Envelope = {
    data?: {
        id?: string;
        /**
         * Operation-specific payload, shaped by the template or operation that ran.
         * The keys are your template's, so the object itself is left open here.
         *
         * Extraction and zero-shot fill it with one entry per extracted field, and
         * each entry is an `ExtractedField`: the value, how certain the model is of
         * it, and — when the value was visually located on the page — where it was
         * read from. A table-shaped field carries an `items` array instead, whose
         * rows hold `ExtractedField` cells under the same keys.
         *
         * Source coordinates follow one convention, the same on every engine:
         *
         * - `page` is 1-indexed, and never past the document's last page.
         * - `bbox` is `[x0, y0, x1, y1]` as fractions of the page size with the
         * origin at the top-left, so `x0,y0` is the top-left corner and `x1,y1`
         * the bottom-right. Values are clamped into `0`–`1` and the corners are
         * ordered, so `x0 <= x1` and `y0 <= y1` always hold.
         * - `page`, `bbox` and `bbox_confidence` are omitted **together** for any
         * value the model could not locate on the page — a computed total, for
         * instance. Their absence is not an error, and a field object carrying
         * none of the three is ordinary.
         *
         * Every confidence this API returns is a number from `0` to `100`,
         * `bbox_confidence` included. There is no second scale to convert from.
         *
         * A document job's stored `result.json` holds the same field entries,
         * sanitized the same way, so the asynchronous answer agrees with the
         * synchronous one for the same document. It wraps them differently — see
         * `outputReference`.
         *
         */
        metadata?: {
            [key: string]: unknown;
        };
        createdDate?: string;
        /**
         * `/Document/classifier` only: one entry per uploaded file.
         *
         */
        results?: Array<ClassificationResult>;
        /**
         * `/Document/zero-shot` only: the document type the model recognized.
         */
        documentType?: string;
        /**
         * `/Document/zero-shot` only: certainty in `documentType`.
         */
        confidence?: number;
        /**
         * `/Document/extraction` only. Always `false`: fraud screening is advisory
         * and never withholds the extraction. Kept for clients that already read it.
         *
         */
        fraudBlocked?: boolean;
        /**
         * `/Document/extraction` only: the fraud screening that ran on this
         * document. Null when screening was disabled, not enabled for the tenant,
         * or failed.
         *
         */
        fraudRequestId?: string | null;
        /**
         * `/Document/extraction` only: the input-quality pre-flight. Null when it
         * did not run. On a `2` (block) verdict the extraction did not run and
         * `metadata` is null; on a `1` (warn) it ran and this carries the findings.
         *
         */
        quality?: QualityAssessment | null;
        /**
         * `/Document/crop` only: signed URLs of the cropped images.
         */
        imageUrls?: Array<string> | null;
        /**
         * `/Document/crop` only: each document found on the page, with where it sits.
         */
        documents?: Array<CropDocument>;
        /**
         * `/Document/crop` only: signed URL of the composite image, when one was produced.
         */
        compositeImageUrl?: string | null;
        /**
         * `/Document/facematch` only: identifies this comparison. Facematch carries no `id`.
         */
        requestId?: string;
        /**
         * `/Document/facematch` only: the face found, or not, in each uploaded document.
         */
        extractions?: Array<FaceExtraction>;
        /**
         * `/Document/facematch` only: the selfie compared against each document face.
         */
        matches?: Array<FaceMatch>;
    };
    meta?: ServiceResponseMeta;
    hasErrors?: boolean;
};

/**
 * One extracted field: the value, how certain the model is of it, and where on the
 * document it was read from. These are the objects that fill `data.metadata`, and
 * the cells inside a table-shaped field's `items` rows.
 *
 * The three location keys are present or absent together — see `data.metadata` for
 * the coordinate convention they follow.
 *
 */
export type ExtractedField = {
    /**
     * The extracted value, or `null` when the field was not found.
     */
    value?: string | null;
    /**
     * Certainty in the value, from `0` to `100`. This is the one confidence scale
     * the API uses; `bbox_confidence` is on the same one.
     *
     */
    confidence?: number;
    /**
     * 1-indexed page the value was read from. Absent when the value could not be
     * located on the page.
     *
     */
    page?: number;
    bbox?: BoundingBox;
    /**
     * Certainty in the location, from `0` to `100` — the same scale as `confidence`,
     * not a `0`–`1` fraction. Absent whenever `bbox` is.
     *
     */
    bbox_confidence?: number;
};

/**
 * Where a value sits on its page, as `[x0, y0, x1, y1]` fractions of the page size
 * with the origin at the top-left: `x0,y0` is the top-left corner and `x1,y1` the
 * bottom-right. Fractions rather than pixels, so the box survives any rendering
 * scale — multiply by the width and height you draw the page at.
 *
 */
export type BoundingBox = [
    number,
    number,
    number,
    number
];

export type ClassificationResult = {
    /**
     * The uploaded file this entry classifies.
     */
    fileName?: string;
    documentType?: string;
    /**
     * Certainty in `documentType`.
     */
    confidence?: number;
    pages?: number | null;
    /**
     * The template the document type resolves to, when one is configured.
     */
    templateId?: string | null;
    /**
     * The matched template's schema. Null when `templateId` is, or the template has no schema yet.
     */
    templateMetadata?: string | null;
};

/**
 * `0` pass, `1` warn, `2` block. Sent as the number, not the name.
 */
export type QualityVerdict = 0 | 1 | 2;

export type QualityAssessment = {
    /**
     * The worst level across `findings`; `0` when there are none.
     */
    overall: QualityVerdict;
    /**
     * Each probe that did not pass. Passing probes are left out.
     */
    findings: Array<QualityFinding>;
};

export type QualityFinding = {
    /**
     * The check that crossed its threshold, such as `blur` or `resolution`.
     */
    probe: string;
    level: QualityVerdict;
    measured: number;
    threshold: number;
    message: string;
};

export type CropDocument = {
    /**
     * Where the document sits on the source image.
     */
    box2D?: Array<number>;
    /**
     * The document's outline on the source image, as a list of points.
     */
    mask?: Array<Array<number>>;
    side?: string;
    /**
     * The detected document type.
     */
    type?: string;
    confidence?: number | null;
    /**
     * Signed URL of this document's crop.
     */
    imageUrl?: string;
};

export type FaceExtraction = {
    sourceDocumentId?: string;
    hasFace?: boolean;
    documentType?: string;
    /**
     * Signed URL of the face crop. Null when none was produced.
     */
    cropSignedUrl?: string | null;
};

export type FaceMatch = {
    sourceDocumentId?: string;
    selfieDocumentId?: string;
    /**
     * Similarity between the selfie and the document face.
     */
    score?: number;
    matched?: boolean;
    tooManyFaces?: boolean;
};

export type DocumentJobOperation = 'Extraction' | 'Classification' | 'ZeroShot' | 'Crop' | 'Split' | 'Redaction' | 'Facematch';

export type DocumentJobSubmitOperation = 'Extraction' | 'Classification' | 'ZeroShot' | 'Crop' | 'Split' | 'Facematch';

export type DocumentJobStatus = 'Queued' | 'Processing' | 'Succeeded' | 'Failed' | 'Cancelled';

export type DocumentJobSubmitStatus = 'Queued';

export type ServiceResponseMeta = {
    httpStatusCode: number;
    messages?: Array<string>;
    errors?: Array<ApiError>;
    creditsConsumed?: number | null;
};

export type ApiError = {
    code: string;
    message: string;
    field?: string | null;
    retryable: boolean;
    details?: {
        [key: string]: string;
    } | null;
};

export type Artifact = {
    /**
     * Pass this as a job's `inputReference`. Reusable until it expires — treat
     * it as opaque rather than parsing it.
     *
     */
    reference: string;
    /**
     * The stored name. Characters outside `A-Z a-z 0-9 . _ -` are replaced and
     * long names are truncated, so this can differ from what you sent. The
     * extension is always preserved.
     *
     */
    fileName: string;
    /**
     * The type the bytes were stored under. A non-image document is normalized
     * to `application/pdf` before storage, so this can differ from what you
     * uploaded.
     *
     */
    contentType: string;
    /**
     * Size of the stored document, which is not the size you sent when it was normalized.
     */
    sizeBytes: number;
    /**
     * When the reference stops resolving — 7 days from upload. Reads after this
     * answer `410`.
     *
     */
    expiresAt: string;
};

export type ArtifactUploadEnvelope = {
    data: Artifact;
    meta: ServiceResponseMeta;
    hasErrors: boolean;
};

export type ServiceErrorEnvelope = {
    data: {
        [key: string]: unknown;
    } | null;
    meta: ServiceResponseMeta;
    hasErrors: boolean;
};

export type DocumentJobSubmission = {
    jobId: string;
    status: DocumentJobSubmitStatus;
    statusUrl: string;
    retryAfterSeconds: number;
};

export type DocumentJobList = {
    jobs: Array<DocumentJob>;
    nextCursor?: string | null;
    hasMore: boolean;
    limit: number;
};

export type Template = {
    id: string;
    name: string;
    description?: string | null;
    /**
     * Only finished templates are returned by this endpoint.
     */
    status: 'Finished';
};

export type TemplateList = {
    templates: Array<Template>;
    nextCursor?: string | null;
    hasMore: boolean;
    limit: number;
};

export type DocumentJobCancellation = {
    jobId: string;
    cancellationRequested: boolean;
};

export type DocumentJobSubmissionEnvelope = {
    data: DocumentJobSubmission;
    meta: ServiceResponseMeta;
    hasErrors: boolean;
};

export type DocumentJobEnvelope = {
    data: DocumentJob;
    meta: ServiceResponseMeta;
    hasErrors: boolean;
};

export type DocumentJobListEnvelope = {
    data: DocumentJobList;
    meta: ServiceResponseMeta;
    hasErrors: boolean;
};

export type TemplateListEnvelope = {
    data: TemplateList;
    meta: ServiceResponseMeta;
    hasErrors: boolean;
};

export type DocumentJobCancellationEnvelope = {
    data: DocumentJobCancellation;
    meta: ServiceResponseMeta;
    hasErrors: boolean;
};

export type DocumentJob = {
    jobId?: string;
    operation?: DocumentJobOperation;
    status?: DocumentJobStatus;
    /**
     * The finished extraction template explicitly selected when the job was
     * submitted. Null when the job did not use a template. Obtain available ids
     * from `GET /api/v1/templates`; synchronous `/Document*` endpoints always
     * select a tenant template from the document and do not take this parameter.
     *
     */
    templateId?: string | null;
    /**
     * Where the finished result is stored, as an `artifact://` reference. Read it
     * with `GET /api/v1/artifacts/content`. Null until the job succeeds, and always
     * null for `Redaction`, which has its own download route.
     *
     * For `Extraction` and `ZeroShot` its field entries are the same
     * `ExtractedField` objects a synchronous call returns for that document — same
     * source-coordinate convention, same `0`-`100` confidence scale.
     *
     * The stored `result.json` is not the response envelope and does not repeat its
     * casing: it holds the extraction result directly, with `Metadata` where the
     * synchronous body has `data.metadata`. The field names inside are your
     * template's either way.
     *
     * Jobs that completed before 2026-09-22 carry a bucket-qualified path rather
     * than an `artifact://` reference; the download accepts both.
     *
     */
    outputReference?: string | null;
    stage?: string | null;
    processedPages?: number | null;
    totalPages?: number | null;
    attemptCount?: number;
    failureCode?: string | null;
    retryable?: boolean;
    startedAt?: string | null;
    completedAt?: string | null;
    cancellationRequestedAt?: string | null;
    expiresAt?: string;
    /**
     * What the job consumed, in credits. Absent — never `0` — while the cost is
     * unknown: a job still queued or running, an operation that is not metered,
     * or one billing could not price. `0` is a real value meaning the job was
     * free. It is a property of the job, so polling a finished job twice reports
     * the same figure; it is not a charge per read.
     *
     */
    creditsConsumed?: number | null;
};

/**
 * `<operation>.processed` when a job succeeds, `<operation>.failed` when it fails
 * or is cancelled. Case-insensitive on input, stored lower-case.
 *
 */
export type WebhookEvent = 'extract.processed' | 'extract.failed' | 'classifier.processed' | 'classifier.failed' | 'zeroshot.processed' | 'zeroshot.failed' | 'crop.processed' | 'crop.failed' | 'split.processed' | 'split.failed' | 'redaction.processed' | 'redaction.failed' | 'facematch.processed' | 'facematch.failed';

export type WebhookEndpointCreateRequest = {
    name: string;
    /**
     * Absolute HTTPS on a public address. Private, loopback and link-local targets are refused.
     */
    url: string;
    events: Array<WebhookEvent>;
    /**
     * Sent on every delivery, for example your receiver's own credential. Stored encrypted.
     */
    headers?: {
        [key: string]: string;
    } | null;
    /**
     * Sent **instead of** the event payload when set. Leave it unset to receive
     * the job fields.
     *
     */
    body?: string | null;
};

export type WebhookEndpointUpdateRequest = {
    /**
     * Ignored. The endpoint is the one named in the path.
     */
    id?: string;
    name: string;
    /**
     * Changing it rotates the signing secret.
     */
    url: string;
    events: Array<WebhookEvent>;
    headers?: {
        [key: string]: string;
    } | null;
    body?: string | null;
    /**
     * An inactive endpoint is kept but receives nothing.
     */
    isActive?: boolean;
};

export type WebhookEndpoint = {
    id: string;
    name: string;
    url: string;
    events: Array<WebhookEvent>;
    headers?: {
        [key: string]: string;
    } | null;
    body?: string | null;
    isActive: boolean;
    /**
     * Which environment's events this endpoint receives. Read-only: it is taken
     * from the API key that registered the endpoint, never from the request body,
     * so a sandbox key's endpoint can never be sent production events and a
     * production key's endpoint can never be sent sandbox ones.
     *
     */
    environment?: 'production' | 'sandbox';
    createdWhen: string;
    changedWhen?: string | null;
    /**
     * The new signing secret, only on the update response that rotated it
     * because `url` changed. Null everywhere else.
     *
     */
    secret?: string | null;
};

export type WebhookEndpointList = {
    endpoints: Array<WebhookEndpoint>;
};

export type WebhookEndpointCreated = {
    endpoint: WebhookEndpoint;
    /**
     * The signing secret. Shown once — store it now.
     */
    secret: string;
};

export type WebhookEndpointDeletion = {
    deleted: boolean;
};

export type WebhookEndpointListEnvelope = {
    data: WebhookEndpointList;
    meta: ServiceResponseMeta;
    hasErrors: boolean;
};

export type WebhookEndpointCreatedEnvelope = {
    data: WebhookEndpointCreated;
    meta: ServiceResponseMeta;
    hasErrors: boolean;
};

export type WebhookEndpointEnvelope = {
    data: WebhookEndpoint;
    meta: ServiceResponseMeta;
    hasErrors: boolean;
};

export type WebhookEndpointDeletionEnvelope = {
    data: WebhookEndpointDeletion;
    meta: ServiceResponseMeta;
    hasErrors: boolean;
};

export type PortalForm = {
    formId?: number;
    formName?: string;
    formDescription?: string | null;
};

export type PortalChannels = {
    channels?: Array<PortalSendChannel>;
};

export type PortalSendChannel = 'email' | 'sms' | 'whatsapp';

export type PortalMagicLinkRequest = {
    /**
     * Target form, from `GET /api/v1/portal/forms`. Must be greater than zero.
     */
    formId: number;
    /**
     * Recipient display name.
     */
    name: string;
    /**
     * Channel to deliver the link on. Omit it to create the link without
     * sending anything.
     *
     */
    sendChannel?: PortalSendChannel | null;
    /**
     * Required when `sendChannel` is `email`.
     */
    email?: string | null;
    /**
     * Required when `sendChannel` is `sms` or `whatsapp`.
     */
    phone?: string | null;
    /**
     * Recipient tax id.
     */
    taxId?: string | null;
    /**
     * Days until the link expires. A value of zero or less is treated as 30.
     */
    dueDays?: number;
    /**
     * How many times the link may be opened. Null means unlimited; 1 makes it single-use.
     */
    maxAccesses?: number | null;
    /**
     * Internal note kept against the link, never shown to the recipient.
     */
    notes?: string | null;
    /**
     * WhatsApp consent for this recipient, recorded alongside creation. Supply it
     * when consent is not already on file. Omit it when consent is already held.
     * Only WhatsApp records this consent; email and SMS use their own consent rules.
     * When supplied, source and non-blank evidenceText are required for every channel.
     *
     */
    optIn?: PortalMagicLinkOptIn | null;
};

/**
 * A declaration that the recipient agreed to be messaged on WhatsApp.
 */
export type PortalMagicLinkOptIn = {
    /**
     * How the recipient's consent was collected.
     */
    source: 'web_form' | 'contract' | 'in_person' | 'import' | 'api';
    /**
     * Required, non-blank pointer to the proof of consent, such as a contract number, form id or ticket.
     */
    evidenceText: string;
    /**
     * Optional link to the evidence.
     */
    evidenceUrl?: string | null;
    /**
     * When the recipient consented. Defaults to now; supply the original date for older consent. Dates more than one day in the future are rejected.
     */
    collectedWhen?: string | null;
};

export type PortalMagicLink = {
    /**
     * The created magic link.
     */
    id?: number;
    /**
     * The link the recipient opens. Present only on the first create — the token
     * is a one-time secret that is never stored in readable form, so an
     * idempotent replay omits this field.
     *
     */
    url?: string | null;
    /**
     * Whether Cogneris dispatched the link. False when `sendChannel` was omitted or the send was suppressed.
     */
    sent?: boolean;
    /**
     * The channel actually used, when one was.
     */
    sendChannel?: PortalSendChannel | null;
    /**
     * Why delivery was suppressed when sent is false. Null or absent when delivery
     * succeeded or no send was requested. This is an open string; handle unknown values.
     * whatsapp_no_optin and whatsapp_optin_revoked require consent to be recorded;
     * whatsapp_blocked means the recipient asked to stop and consent cannot override it;
     * provider_error is transient and may be retried. The link exists even if sending
     * was suppressed; use the returned url when present.
     *
     */
    sendSuppressionReason?: string | null;
};

/**
 * RFC 9457 problem document, sent as `application/problem+json`.
 */
export type ProblemDetails = {
    /**
     * Opaque stable identifier for the error class.
     */
    type?: string;
    title?: string;
    status?: number;
    detail?: string | null;
    /**
     * The path that produced the error.
     */
    instance?: string;
    /**
     * Stable machine-readable error code — branch on this.
     */
    code?: string;
    /**
     * Also returned in the `x-correlation-id` header.
     */
    correlationId?: string;
    retryable?: boolean;
    /**
     * The request field at fault, on validation failures.
     */
    field?: string | null;
    errors?: Array<{
        code?: string;
        message?: string;
        /**
         * Present on validation failures.
         */
        field?: string | null;
        retryable?: boolean;
        details?: {
            [key: string]: string;
        } | null;
    }>;
};

/**
 * Your identifier for this write, so a retry cannot register or change an
 * endpoint twice. Reuse it only to repeat the identical request. Kept for 24
 * hours.
 *
 */
export type WebhookIdempotencyKey = string;

export type SingleFile = {
    file: Blob | File;
};

export type ExtractDocumentData = {
    body: {
        /**
         * The document to extract from.
         */
        file: Blob | File;
        /**
         * Free-text instruction appended to the model prompt. Use it to ask
         * for extra fields, enforce formatting, or narrow the scope.
         *
         */
        ComplementaryPrompt?: string;
    };
    path?: never;
    query?: never;
    url: '/Document/extraction';
};

export type ExtractDocumentErrors = {
    /**
     * The request is invalid. Refused before processing — malformed or unsafe — it
     * is a problem document; refused by processing itself, such as a missing file,
     * it is the service envelope with the reason in `meta.errors`.
     *
     */
    400: ProblemDetails;
    /**
     * Missing or invalid API key. Both `xtkt_live_` (production) and `xtkt_test_`
     * (sandbox) prefixes are accepted, but the key must also be valid and active.
     *
     */
    401: ProblemDetails;
    /**
     * The key is valid but not allowed to make this request.
     */
    403: ProblemDetails;
    /**
     * Nothing answers at this address for this tenant.
     */
    404: ProblemDetails;
    /**
     * The request conflicts with the current state of what it acts on.
     */
    409: ProblemDetails;
    /**
     * Over the size limit — 10 MB, or 500 MB on `/Document/split`.
     */
    413: unknown;
    /**
     * Extension outside the supported list.
     */
    415: unknown;
    /**
     * Over 50 requests in the current 1-minute window for this key, answered as a
     * problem document; or the document admission quota is exhausted, answered as
     * the service envelope with `ADMISSION_QUOTA_EXCEEDED`. Both are retryable.
     *
     */
    429: ProblemDetails;
    /**
     * Unexpected failure. `correlationId` identifies the request — quote it when
     * you contact support.
     *
     */
    500: ProblemDetails;
};

export type ExtractDocumentError = ExtractDocumentErrors[keyof ExtractDocumentErrors];

export type ExtractDocumentResponses = {
    /**
     * The service envelope. `data.metadata` is shaped by the template or operation
     * that ran, so its fields vary by document type. What does not vary is the shape of
     * each field inside it — see `ExtractedField` for the value, confidence and source
     * coordinates every extracted field carries.
     *
     */
    200: Envelope;
};

export type ExtractDocumentResponse = ExtractDocumentResponses[keyof ExtractDocumentResponses];

export type ClassifyDocumentsData = {
    body: {
        /**
         * One or more files to classify.
         */
        files: Array<Blob | File>;
    };
    path?: never;
    query?: never;
    url: '/Document/classifier';
};

export type ClassifyDocumentsErrors = {
    /**
     * The request is invalid. Refused before processing — malformed or unsafe — it
     * is a problem document; refused by processing itself, such as a missing file,
     * it is the service envelope with the reason in `meta.errors`.
     *
     */
    400: ProblemDetails;
    /**
     * Missing or invalid API key. Both `xtkt_live_` (production) and `xtkt_test_`
     * (sandbox) prefixes are accepted, but the key must also be valid and active.
     *
     */
    401: ProblemDetails;
    /**
     * The key is valid but not allowed to make this request.
     */
    403: ProblemDetails;
    /**
     * Nothing answers at this address for this tenant.
     */
    404: ProblemDetails;
    /**
     * The request conflicts with the current state of what it acts on.
     */
    409: ProblemDetails;
    /**
     * Over the size limit — 10 MB, or 500 MB on `/Document/split`.
     */
    413: unknown;
    /**
     * Extension outside the supported list.
     */
    415: unknown;
    /**
     * Over 50 requests in the current 1-minute window for this key, answered as a
     * problem document; or the document admission quota is exhausted, answered as
     * the service envelope with `ADMISSION_QUOTA_EXCEEDED`. Both are retryable.
     *
     */
    429: ProblemDetails;
    /**
     * Unexpected failure. `correlationId` identifies the request — quote it when
     * you contact support.
     *
     */
    500: ProblemDetails;
};

export type ClassifyDocumentsError = ClassifyDocumentsErrors[keyof ClassifyDocumentsErrors];

export type ClassifyDocumentsResponses = {
    /**
     * The service envelope. `data.metadata` is shaped by the template or operation
     * that ran, so its fields vary by document type. What does not vary is the shape of
     * each field inside it — see `ExtractedField` for the value, confidence and source
     * coordinates every extracted field carries.
     *
     */
    200: Envelope;
};

export type ClassifyDocumentsResponse = ClassifyDocumentsResponses[keyof ClassifyDocumentsResponses];

export type ZeroShotDocumentData = {
    body: SingleFile;
    path?: never;
    query?: never;
    url: '/Document/zero-shot';
};

export type ZeroShotDocumentErrors = {
    /**
     * The request is invalid. Refused before processing — malformed or unsafe — it
     * is a problem document; refused by processing itself, such as a missing file,
     * it is the service envelope with the reason in `meta.errors`.
     *
     */
    400: ProblemDetails;
    /**
     * Missing or invalid API key. Both `xtkt_live_` (production) and `xtkt_test_`
     * (sandbox) prefixes are accepted, but the key must also be valid and active.
     *
     */
    401: ProblemDetails;
    /**
     * The key is valid but not allowed to make this request.
     */
    403: ProblemDetails;
    /**
     * Nothing answers at this address for this tenant.
     */
    404: ProblemDetails;
    /**
     * The request conflicts with the current state of what it acts on.
     */
    409: ProblemDetails;
    /**
     * Over the size limit — 10 MB, or 500 MB on `/Document/split`.
     */
    413: unknown;
    /**
     * Extension outside the supported list.
     */
    415: unknown;
    /**
     * Over 50 requests in the current 1-minute window for this key, answered as a
     * problem document; or the document admission quota is exhausted, answered as
     * the service envelope with `ADMISSION_QUOTA_EXCEEDED`. Both are retryable.
     *
     */
    429: ProblemDetails;
    /**
     * Unexpected failure. `correlationId` identifies the request — quote it when
     * you contact support.
     *
     */
    500: ProblemDetails;
};

export type ZeroShotDocumentError = ZeroShotDocumentErrors[keyof ZeroShotDocumentErrors];

export type ZeroShotDocumentResponses = {
    /**
     * The service envelope. `data.metadata` is shaped by the template or operation
     * that ran, so its fields vary by document type. What does not vary is the shape of
     * each field inside it — see `ExtractedField` for the value, confidence and source
     * coordinates every extracted field carries.
     *
     */
    200: Envelope;
};

export type ZeroShotDocumentResponse = ZeroShotDocumentResponses[keyof ZeroShotDocumentResponses];

export type CropDocumentData = {
    body: SingleFile;
    path?: never;
    query?: never;
    url: '/Document/crop';
};

export type CropDocumentErrors = {
    /**
     * The request is invalid. Refused before processing — malformed or unsafe — it
     * is a problem document; refused by processing itself, such as a missing file,
     * it is the service envelope with the reason in `meta.errors`.
     *
     */
    400: ProblemDetails;
    /**
     * Missing or invalid API key. Both `xtkt_live_` (production) and `xtkt_test_`
     * (sandbox) prefixes are accepted, but the key must also be valid and active.
     *
     */
    401: ProblemDetails;
    /**
     * The key is valid but not allowed to make this request.
     */
    403: ProblemDetails;
    /**
     * Nothing answers at this address for this tenant.
     */
    404: ProblemDetails;
    /**
     * The request conflicts with the current state of what it acts on.
     */
    409: ProblemDetails;
    /**
     * Over the size limit — 10 MB, or 500 MB on `/Document/split`.
     */
    413: unknown;
    /**
     * Extension outside the supported list.
     */
    415: unknown;
    /**
     * Over 50 requests in the current 1-minute window for this key, answered as a
     * problem document; or the document admission quota is exhausted, answered as
     * the service envelope with `ADMISSION_QUOTA_EXCEEDED`. Both are retryable.
     *
     */
    429: ProblemDetails;
    /**
     * Unexpected failure. `correlationId` identifies the request — quote it when
     * you contact support.
     *
     */
    500: ProblemDetails;
};

export type CropDocumentError = CropDocumentErrors[keyof CropDocumentErrors];

export type CropDocumentResponses = {
    /**
     * The service envelope. `data.metadata` is shaped by the template or operation
     * that ran, so its fields vary by document type. What does not vary is the shape of
     * each field inside it — see `ExtractedField` for the value, confidence and source
     * coordinates every extracted field carries.
     *
     */
    200: Envelope;
};

export type CropDocumentResponse = CropDocumentResponses[keyof CropDocumentResponses];

export type SplitDocumentData = {
    body: SingleFile;
    path?: never;
    query?: never;
    url: '/Document/split';
};

export type SplitDocumentErrors = {
    /**
     * The request is invalid. Refused before processing — malformed or unsafe — it
     * is a problem document; refused by processing itself, such as a missing file,
     * it is the service envelope with the reason in `meta.errors`.
     *
     */
    400: ProblemDetails;
    /**
     * Missing or invalid API key. Both `xtkt_live_` (production) and `xtkt_test_`
     * (sandbox) prefixes are accepted, but the key must also be valid and active.
     *
     */
    401: ProblemDetails;
    /**
     * The key is valid but not allowed to make this request.
     */
    403: ProblemDetails;
    /**
     * Nothing answers at this address for this tenant.
     */
    404: ProblemDetails;
    /**
     * The request conflicts with the current state of what it acts on.
     */
    409: ProblemDetails;
    /**
     * Over the size limit — 10 MB, or 500 MB on `/Document/split`.
     */
    413: unknown;
    /**
     * Extension outside the supported list.
     */
    415: unknown;
    /**
     * Over 50 requests in the current 1-minute window for this key, answered as a
     * problem document; or the document admission quota is exhausted, answered as
     * the service envelope with `ADMISSION_QUOTA_EXCEEDED`. Both are retryable.
     *
     */
    429: ProblemDetails;
    /**
     * Unexpected failure. `correlationId` identifies the request — quote it when
     * you contact support.
     *
     */
    500: ProblemDetails;
};

export type SplitDocumentError = SplitDocumentErrors[keyof SplitDocumentErrors];

export type SplitDocumentResponses = {
    /**
     * The service envelope. `data.metadata` is shaped by the template or operation
     * that ran, so its fields vary by document type. What does not vary is the shape of
     * each field inside it — see `ExtractedField` for the value, confidence and source
     * coordinates every extracted field carries.
     *
     */
    200: Envelope;
};

export type SplitDocumentResponse = SplitDocumentResponses[keyof SplitDocumentResponses];

export type FaceMatchDocumentData = {
    body: {
        /**
         * The selfie to compare.
         */
        selfie: Blob | File;
        /**
         * One or more identity documents to compare against.
         */
        documents: Array<Blob | File>;
    };
    path?: never;
    query?: never;
    url: '/Document/facematch';
};

export type FaceMatchDocumentErrors = {
    /**
     * The request is invalid. Refused before processing — malformed or unsafe — it
     * is a problem document; refused by processing itself, such as a missing file,
     * it is the service envelope with the reason in `meta.errors`.
     *
     */
    400: ProblemDetails;
    /**
     * Missing or invalid API key. Both `xtkt_live_` (production) and `xtkt_test_`
     * (sandbox) prefixes are accepted, but the key must also be valid and active.
     *
     */
    401: ProblemDetails;
    /**
     * The key is valid but not allowed to make this request.
     */
    403: ProblemDetails;
    /**
     * Nothing answers at this address for this tenant.
     */
    404: ProblemDetails;
    /**
     * The request conflicts with the current state of what it acts on.
     */
    409: ProblemDetails;
    /**
     * Over the size limit — 10 MB, or 500 MB on `/Document/split`.
     */
    413: unknown;
    /**
     * Extension outside the supported list.
     */
    415: unknown;
    /**
     * Over 50 requests in the current 1-minute window for this key, answered as a
     * problem document; or the document admission quota is exhausted, answered as
     * the service envelope with `ADMISSION_QUOTA_EXCEEDED`. Both are retryable.
     *
     */
    429: ProblemDetails;
    /**
     * Unexpected failure. `correlationId` identifies the request — quote it when
     * you contact support.
     *
     */
    500: ProblemDetails;
};

export type FaceMatchDocumentError = FaceMatchDocumentErrors[keyof FaceMatchDocumentErrors];

export type FaceMatchDocumentResponses = {
    /**
     * The service envelope. `data.metadata` is shaped by the template or operation
     * that ran, so its fields vary by document type. What does not vary is the shape of
     * each field inside it — see `ExtractedField` for the value, confidence and source
     * coordinates every extracted field carries.
     *
     */
    200: Envelope;
};

export type FaceMatchDocumentResponse = FaceMatchDocumentResponses[keyof FaceMatchDocumentResponses];

export type UploadArtifactData = {
    body: {
        /**
         * The document a job will consume. Same accepted extensions and the
         * same 10 MB limit as the synchronous endpoints.
         *
         */
        file: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/api/v1/artifacts';
};

export type UploadArtifactErrors = {
    /**
     * The request is invalid. Refused before processing — malformed or unsafe — it
     * is a problem document; refused by processing itself, such as a missing file,
     * it is the service envelope with the reason in `meta.errors`.
     *
     */
    400: ProblemDetails;
    /**
     * Missing or invalid API key. Both `xtkt_live_` (production) and `xtkt_test_`
     * (sandbox) prefixes are accepted, but the key must also be valid and active.
     *
     */
    401: ProblemDetails;
    /**
     * The key is valid but not allowed to make this request.
     */
    403: ProblemDetails;
    /**
     * Nothing answers at this address for this tenant.
     */
    404: ProblemDetails;
    /**
     * The request conflicts with the current state of what it acts on.
     */
    409: ProblemDetails;
    /**
     * Over the size limit — 10 MB, or 500 MB on `/Document/split`.
     */
    413: unknown;
    /**
     * Extension outside the supported list.
     */
    415: unknown;
    /**
     * The document was rejected by the security policy, or could not be
     * converted safely. The `code` says which.
     *
     */
    422: ServiceErrorEnvelope;
    /**
     * Over 50 requests in the current 1-minute window for this key, answered as a
     * problem document; or the document admission quota is exhausted, answered as
     * the service envelope with `ADMISSION_QUOTA_EXCEEDED`. Both are retryable.
     *
     */
    429: ProblemDetails;
    /**
     * Unexpected failure. `correlationId` identifies the request — quote it when
     * you contact support.
     *
     */
    500: ProblemDetails;
    /**
     * Document admission is temporarily unavailable. Marked retryable — back
     * off and upload again.
     *
     */
    503: ServiceErrorEnvelope;
};

export type UploadArtifactError = UploadArtifactErrors[keyof UploadArtifactErrors];

export type UploadArtifactResponses = {
    /**
     * Stored.
     */
    201: ArtifactUploadEnvelope;
};

export type UploadArtifactResponse = UploadArtifactResponses[keyof UploadArtifactResponses];

export type DownloadArtifactData = {
    body?: never;
    path?: never;
    query: {
        /**
         * An `artifact://` reference, or the bucket-qualified form an older job
         * returned. Pass back exactly what you were given.
         *
         */
        reference: string;
    };
    url: '/api/v1/artifacts/content';
};

export type DownloadArtifactErrors = {
    /**
     * The reference is missing, unreadable, or not one this tenant can read.
     * A reference belonging to another tenant answers here, not `403` — the
     * response does not reveal whether it exists.
     *
     */
    400: ServiceErrorEnvelope;
    /**
     * Missing or invalid API key. Both `xtkt_live_` (production) and `xtkt_test_`
     * (sandbox) prefixes are accepted, but the key must also be valid and active.
     *
     */
    401: ProblemDetails;
    /**
     * The key is valid but not allowed to make this request.
     */
    403: ProblemDetails;
    /**
     * No artifact with that reference in this tenant.
     */
    404: ServiceErrorEnvelope;
    /**
     * The request conflicts with the current state of what it acts on.
     */
    409: ProblemDetails;
    /**
     * The reference was valid and has expired. Distinct from `404` on purpose:
     * retrying will never succeed, so upload again.
     *
     */
    410: ServiceErrorEnvelope;
    /**
     * Over 50 requests in the current 1-minute window for this key.
     */
    429: ProblemDetails;
    /**
     * Unexpected failure. `correlationId` identifies the request — quote it when
     * you contact support.
     *
     */
    500: ProblemDetails;
};

export type DownloadArtifactError = DownloadArtifactErrors[keyof DownloadArtifactErrors];

export type DownloadArtifactResponses = {
    /**
     * A job result document.
     */
    200: {
        [key: string]: unknown;
    };
};

export type DownloadArtifactResponse = DownloadArtifactResponses[keyof DownloadArtifactResponses];

export type ListDocumentJobsData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
    };
    url: '/api/v1/document-jobs';
};

export type ListDocumentJobsErrors = {
    /**
     * The request is invalid. Refused before processing — malformed or unsafe — it
     * is a problem document; refused by processing itself, such as a missing file,
     * it is the service envelope with the reason in `meta.errors`.
     *
     */
    400: ProblemDetails;
    /**
     * Missing or invalid API key. Both `xtkt_live_` (production) and `xtkt_test_`
     * (sandbox) prefixes are accepted, but the key must also be valid and active.
     *
     */
    401: ProblemDetails;
    /**
     * The key is valid but not allowed to make this request.
     */
    403: ProblemDetails;
    /**
     * Nothing answers at this address for this tenant.
     */
    404: ProblemDetails;
    /**
     * The request conflicts with the current state of what it acts on.
     */
    409: ProblemDetails;
    /**
     * Over 50 requests in the current 1-minute window for this key.
     */
    429: ProblemDetails;
    /**
     * Unexpected failure. `correlationId` identifies the request — quote it when
     * you contact support.
     *
     */
    500: ProblemDetails;
};

export type ListDocumentJobsError = ListDocumentJobsErrors[keyof ListDocumentJobsErrors];

export type ListDocumentJobsResponses = {
    /**
     * Jobs for the tenant.
     */
    200: DocumentJobListEnvelope;
};

export type ListDocumentJobsResponse = ListDocumentJobsResponses[keyof ListDocumentJobsResponses];

export type SubmitDocumentJobData = {
    body: {
        /**
         * The work to run. A finished classifier is a published, immutable
         * template version: updates are rejected, and a changed definition must
         * be published as a new classifier with a new id.
         *
         */
        operation: DocumentJobSubmitOperation;
        /**
         * The `reference` returned by `POST /api/v1/artifacts`. That upload
         * is the only way to obtain one, and it can back more than one job
         * until it expires.
         *
         */
        inputReference: string;
        /**
         * Extraction only: the id of one of your tenant's finished templates,
         * whose schema drives the extraction. Omit it and the platform picks the
         * template from the document, as the synchronous endpoint does. Sent with
         * any other operation, the job is refused with `400`. An id the platform
         * cannot resolve to a finished template of yours is refused too; the job
         * never falls back to a generic extraction without the schema you asked for.
         *
         */
        templateId?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/v1/document-jobs';
};

export type SubmitDocumentJobErrors = {
    /**
     * The request is invalid. Refused before processing — malformed or unsafe — it
     * is a problem document; refused by processing itself, such as a missing file,
     * it is the service envelope with the reason in `meta.errors`.
     *
     */
    400: ProblemDetails;
    /**
     * Missing or invalid API key. Both `xtkt_live_` (production) and `xtkt_test_`
     * (sandbox) prefixes are accepted, but the key must also be valid and active.
     *
     */
    401: ProblemDetails;
    /**
     * The key is valid but not allowed to make this request.
     */
    403: ProblemDetails;
    /**
     * Nothing answers at this address for this tenant.
     */
    404: ProblemDetails;
    /**
     * The request conflicts with the current state of what it acts on.
     */
    409: ProblemDetails;
    /**
     * The requested extraction template cannot be used for this job.
     * `template_unknown` means the id is not a finished template in the API
     * key's tenant; `template_not_applicable` means the finished template does
     * not apply to the submitted job.
     *
     */
    422: ServiceErrorEnvelope;
    /**
     * Over 50 requests in the current 1-minute window for this key.
     */
    429: ProblemDetails;
    /**
     * Unexpected failure. `correlationId` identifies the request — quote it when
     * you contact support.
     *
     */
    500: ProblemDetails;
};

export type SubmitDocumentJobError = SubmitDocumentJobErrors[keyof SubmitDocumentJobErrors];

export type SubmitDocumentJobResponses = {
    /**
     * Job accepted.
     */
    202: DocumentJobSubmissionEnvelope;
};

export type SubmitDocumentJobResponse = SubmitDocumentJobResponses[keyof SubmitDocumentJobResponses];

export type ListTemplatesData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
        /**
         * The `nextCursor` returned by the preceding page.
         */
        cursor?: string;
    };
    url: '/api/v1/templates';
};

export type ListTemplatesErrors = {
    /**
     * The request is invalid. Refused before processing — malformed or unsafe — it
     * is a problem document; refused by processing itself, such as a missing file,
     * it is the service envelope with the reason in `meta.errors`.
     *
     */
    400: ProblemDetails;
    /**
     * Missing or invalid API key. Both `xtkt_live_` (production) and `xtkt_test_`
     * (sandbox) prefixes are accepted, but the key must also be valid and active.
     *
     */
    401: ProblemDetails;
    /**
     * The key is valid but not allowed to make this request.
     */
    403: ProblemDetails;
    /**
     * Nothing answers at this address for this tenant.
     */
    404: ProblemDetails;
    /**
     * The request conflicts with the current state of what it acts on.
     */
    409: ProblemDetails;
    /**
     * Over 50 requests in the current 1-minute window for this key.
     */
    429: ProblemDetails;
    /**
     * Unexpected failure. `correlationId` identifies the request — quote it when
     * you contact support.
     *
     */
    500: ProblemDetails;
};

export type ListTemplatesError = ListTemplatesErrors[keyof ListTemplatesErrors];

export type ListTemplatesResponses = {
    /**
     * Finished templates for the tenant.
     */
    200: TemplateListEnvelope;
};

export type ListTemplatesResponse = ListTemplatesResponses[keyof ListTemplatesResponses];

export type GetDocumentJobData = {
    body?: never;
    path: {
        jobId: string;
    };
    query?: never;
    url: '/api/v1/document-jobs/{jobId}';
};

export type GetDocumentJobErrors = {
    /**
     * The request is invalid. Refused before processing — malformed or unsafe — it
     * is a problem document; refused by processing itself, such as a missing file,
     * it is the service envelope with the reason in `meta.errors`.
     *
     */
    400: ProblemDetails;
    /**
     * Missing or invalid API key. Both `xtkt_live_` (production) and `xtkt_test_`
     * (sandbox) prefixes are accepted, but the key must also be valid and active.
     *
     */
    401: ProblemDetails;
    /**
     * The key is valid but not allowed to make this request.
     */
    403: ProblemDetails;
    /**
     * No job with that id in this tenant.
     */
    404: ServiceErrorEnvelope;
    /**
     * The request conflicts with the current state of what it acts on.
     */
    409: ProblemDetails;
    /**
     * Over 50 requests in the current 1-minute window for this key.
     */
    429: ProblemDetails;
    /**
     * Unexpected failure. `correlationId` identifies the request — quote it when
     * you contact support.
     *
     */
    500: ProblemDetails;
};

export type GetDocumentJobError = GetDocumentJobErrors[keyof GetDocumentJobErrors];

export type GetDocumentJobResponses = {
    /**
     * The job.
     */
    200: DocumentJobEnvelope;
};

export type GetDocumentJobResponse = GetDocumentJobResponses[keyof GetDocumentJobResponses];

export type CancelDocumentJobData = {
    body?: never;
    path: {
        jobId: string;
    };
    query?: never;
    url: '/api/v1/document-jobs/{jobId}/cancel';
};

export type CancelDocumentJobErrors = {
    /**
     * The request is invalid. Refused before processing — malformed or unsafe — it
     * is a problem document; refused by processing itself, such as a missing file,
     * it is the service envelope with the reason in `meta.errors`.
     *
     */
    400: ProblemDetails;
    /**
     * Missing or invalid API key. Both `xtkt_live_` (production) and `xtkt_test_`
     * (sandbox) prefixes are accepted, but the key must also be valid and active.
     *
     */
    401: ProblemDetails;
    /**
     * The key is valid but not allowed to make this request.
     */
    403: ProblemDetails;
    /**
     * Nothing answers at this address for this tenant.
     */
    404: ProblemDetails;
    /**
     * The job does not exist or can no longer be cancelled.
     */
    409: ServiceErrorEnvelope;
    /**
     * Over 50 requests in the current 1-minute window for this key.
     */
    429: ProblemDetails;
    /**
     * Unexpected failure. `correlationId` identifies the request — quote it when
     * you contact support.
     *
     */
    500: ProblemDetails;
};

export type CancelDocumentJobError = CancelDocumentJobErrors[keyof CancelDocumentJobErrors];

export type CancelDocumentJobResponses = {
    /**
     * Cancellation requested.
     */
    202: DocumentJobCancellationEnvelope;
};

export type CancelDocumentJobResponse = CancelDocumentJobResponses[keyof CancelDocumentJobResponses];

export type ListWebhookEndpointsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/webhook-endpoints';
};

export type ListWebhookEndpointsErrors = {
    /**
     * Invalid request — a `url` that is not absolute HTTPS on a public address, no
     * events, an unknown event, or a missing `Idempotency-Key`. `code` says which.
     *
     */
    400: ProblemDetails;
    /**
     * Missing, invalid or inactive API key.
     */
    401: ProblemDetails;
    /**
     * The key cannot manage webhook endpoints. `webhook.scope_required`: it lacks
     * `webhooks.manage` (or `*`). `webhook.production_key_required`: it is not a
     * production key — endpoints receive production events only.
     *
     */
    403: ProblemDetails;
    /**
     * No endpoint with that id in this tenant.
     */
    404: ProblemDetails;
    /**
     * The `Idempotency-Key` was used with a different body (`idempotency_key_reused`),
     * or the first request with it is still in progress (`idempotency_in_progress`,
     * retryable, with `Retry-After`).
     *
     */
    409: ProblemDetails;
    /**
     * Over 50 requests in the current 1-minute window for this key.
     */
    429: ProblemDetails;
    /**
     * Unexpected failure. Safe to retry a read; retry a write with the same `Idempotency-Key`.
     */
    500: ProblemDetails;
};

export type ListWebhookEndpointsError = ListWebhookEndpointsErrors[keyof ListWebhookEndpointsErrors];

export type ListWebhookEndpointsResponses = {
    /**
     * The tenant's endpoints.
     */
    200: WebhookEndpointListEnvelope;
};

export type ListWebhookEndpointsResponse = ListWebhookEndpointsResponses[keyof ListWebhookEndpointsResponses];

export type CreateWebhookEndpointData = {
    body: WebhookEndpointCreateRequest;
    headers: {
        /**
         * Your identifier for this write, so a retry cannot register or change an
         * endpoint twice. Reuse it only to repeat the identical request. Kept for 24
         * hours.
         *
         */
        'Idempotency-Key': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/webhook-endpoints';
};

export type CreateWebhookEndpointErrors = {
    /**
     * Invalid request — a `url` that is not absolute HTTPS on a public address, no
     * events, an unknown event, or a missing `Idempotency-Key`. `code` says which.
     *
     */
    400: ProblemDetails;
    /**
     * Missing, invalid or inactive API key.
     */
    401: ProblemDetails;
    /**
     * The key cannot manage webhook endpoints. `webhook.scope_required`: it lacks
     * `webhooks.manage` (or `*`). `webhook.production_key_required`: it is not a
     * production key — endpoints receive production events only.
     *
     */
    403: ProblemDetails;
    /**
     * No endpoint with that id in this tenant.
     */
    404: ProblemDetails;
    /**
     * The `Idempotency-Key` was used with a different body (`idempotency_key_reused`),
     * or the first request with it is still in progress (`idempotency_in_progress`,
     * retryable, with `Retry-After`).
     *
     */
    409: ProblemDetails;
    /**
     * Over 50 requests in the current 1-minute window for this key.
     */
    429: ProblemDetails;
    /**
     * Unexpected failure. Safe to retry a read; retry a write with the same `Idempotency-Key`.
     */
    500: ProblemDetails;
};

export type CreateWebhookEndpointError = CreateWebhookEndpointErrors[keyof CreateWebhookEndpointErrors];

export type CreateWebhookEndpointResponses = {
    /**
     * Registered.
     */
    200: WebhookEndpointCreatedEnvelope;
};

export type CreateWebhookEndpointResponse = CreateWebhookEndpointResponses[keyof CreateWebhookEndpointResponses];

export type DeleteWebhookEndpointData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/webhook-endpoints/{id}';
};

export type DeleteWebhookEndpointErrors = {
    /**
     * Invalid request — a `url` that is not absolute HTTPS on a public address, no
     * events, an unknown event, or a missing `Idempotency-Key`. `code` says which.
     *
     */
    400: ProblemDetails;
    /**
     * Missing, invalid or inactive API key.
     */
    401: ProblemDetails;
    /**
     * The key cannot manage webhook endpoints. `webhook.scope_required`: it lacks
     * `webhooks.manage` (or `*`). `webhook.production_key_required`: it is not a
     * production key — endpoints receive production events only.
     *
     */
    403: ProblemDetails;
    /**
     * No endpoint with that id in this tenant.
     */
    404: ProblemDetails;
    /**
     * The `Idempotency-Key` was used with a different body (`idempotency_key_reused`),
     * or the first request with it is still in progress (`idempotency_in_progress`,
     * retryable, with `Retry-After`).
     *
     */
    409: ProblemDetails;
    /**
     * Over 50 requests in the current 1-minute window for this key.
     */
    429: ProblemDetails;
    /**
     * Unexpected failure. Safe to retry a read; retry a write with the same `Idempotency-Key`.
     */
    500: ProblemDetails;
};

export type DeleteWebhookEndpointError = DeleteWebhookEndpointErrors[keyof DeleteWebhookEndpointErrors];

export type DeleteWebhookEndpointResponses = {
    /**
     * Removed.
     */
    200: WebhookEndpointDeletionEnvelope;
};

export type DeleteWebhookEndpointResponse = DeleteWebhookEndpointResponses[keyof DeleteWebhookEndpointResponses];

export type UpdateWebhookEndpointData = {
    body: WebhookEndpointUpdateRequest;
    headers: {
        /**
         * Your identifier for this write, so a retry cannot register or change an
         * endpoint twice. Reuse it only to repeat the identical request. Kept for 24
         * hours.
         *
         */
        'Idempotency-Key': string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/webhook-endpoints/{id}';
};

export type UpdateWebhookEndpointErrors = {
    /**
     * Invalid request — a `url` that is not absolute HTTPS on a public address, no
     * events, an unknown event, or a missing `Idempotency-Key`. `code` says which.
     *
     */
    400: ProblemDetails;
    /**
     * Missing, invalid or inactive API key.
     */
    401: ProblemDetails;
    /**
     * The key cannot manage webhook endpoints. `webhook.scope_required`: it lacks
     * `webhooks.manage` (or `*`). `webhook.production_key_required`: it is not a
     * production key — endpoints receive production events only.
     *
     */
    403: ProblemDetails;
    /**
     * No endpoint with that id in this tenant.
     */
    404: ProblemDetails;
    /**
     * The `Idempotency-Key` was used with a different body (`idempotency_key_reused`),
     * or the first request with it is still in progress (`idempotency_in_progress`,
     * retryable, with `Retry-After`).
     *
     */
    409: ProblemDetails;
    /**
     * Over 50 requests in the current 1-minute window for this key.
     */
    429: ProblemDetails;
    /**
     * Unexpected failure. Safe to retry a read; retry a write with the same `Idempotency-Key`.
     */
    500: ProblemDetails;
};

export type UpdateWebhookEndpointError = UpdateWebhookEndpointErrors[keyof UpdateWebhookEndpointErrors];

export type UpdateWebhookEndpointResponses = {
    /**
     * Replaced.
     */
    200: WebhookEndpointEnvelope;
};

export type UpdateWebhookEndpointResponse = UpdateWebhookEndpointResponses[keyof UpdateWebhookEndpointResponses];

export type ListPortalFormsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/portal/forms';
};

export type ListPortalFormsErrors = {
    /**
     * The request was refused before it was processed — malformed, unsafe, or
     * missing something it needs. `code` says which.
     *
     */
    400: ProblemDetails;
    /**
     * Missing or invalid API key. Both `xtkt_live_` (production) and `xtkt_test_`
     * (sandbox) prefixes are accepted, but the key must also be valid and active.
     *
     */
    401: ProblemDetails;
    /**
     * The key is valid but lacks the scope this endpoint requires —
     * `portal.forms.read` to read, `portal.magiclinks.write` to create. The missing
     * scope is named in the response.
     *
     */
    403: ProblemDetails;
    /**
     * Nothing answers at this address for this tenant.
     */
    404: ProblemDetails;
    /**
     * The request conflicts with the current state of what it acts on.
     */
    409: ProblemDetails;
    /**
     * Over 50 requests in the current 1-minute window for this key.
     */
    429: ProblemDetails;
    /**
     * Unexpected failure. `correlationId` identifies the request — quote it when
     * you contact support.
     *
     */
    500: ProblemDetails;
    /**
     * The Portal service is unreachable. Marked retryable — back off and try again.
     */
    502: ProblemDetails;
};

export type ListPortalFormsError = ListPortalFormsErrors[keyof ListPortalFormsErrors];

export type ListPortalFormsResponses = {
    /**
     * The tenant's forms.
     */
    200: Array<PortalForm>;
};

export type ListPortalFormsResponse = ListPortalFormsResponses[keyof ListPortalFormsResponses];

export type ListPortalChannelsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/portal/available-channels';
};

export type ListPortalChannelsErrors = {
    /**
     * The request was refused before it was processed — malformed, unsafe, or
     * missing something it needs. `code` says which.
     *
     */
    400: ProblemDetails;
    /**
     * Missing or invalid API key. Both `xtkt_live_` (production) and `xtkt_test_`
     * (sandbox) prefixes are accepted, but the key must also be valid and active.
     *
     */
    401: ProblemDetails;
    /**
     * The key is valid but lacks the scope this endpoint requires —
     * `portal.forms.read` to read, `portal.magiclinks.write` to create. The missing
     * scope is named in the response.
     *
     */
    403: ProblemDetails;
    /**
     * Nothing answers at this address for this tenant.
     */
    404: ProblemDetails;
    /**
     * The request conflicts with the current state of what it acts on.
     */
    409: ProblemDetails;
    /**
     * Over 50 requests in the current 1-minute window for this key.
     */
    429: ProblemDetails;
    /**
     * Unexpected failure. `correlationId` identifies the request — quote it when
     * you contact support.
     *
     */
    500: ProblemDetails;
    /**
     * The Portal service is unreachable. Marked retryable — back off and try again.
     */
    502: ProblemDetails;
};

export type ListPortalChannelsError = ListPortalChannelsErrors[keyof ListPortalChannelsErrors];

export type ListPortalChannelsResponses = {
    /**
     * The enabled channels.
     */
    200: PortalChannels;
};

export type ListPortalChannelsResponse = ListPortalChannelsResponses[keyof ListPortalChannelsResponses];

export type CreatePortalMagicLinkData = {
    body: PortalMagicLinkRequest;
    headers?: {
        /**
         * Stable caller-supplied key that makes a retry resolve to the same link.
         */
        'Idempotency-Key'?: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/portal/magic-link';
};

export type CreatePortalMagicLinkErrors = {
    /**
     * A field failed validation — a missing `formId` or `name`, a `sendChannel`
     * outside the allowed set, or a channel whose matching contact field is absent.
     * The offending field is named in `errors[].field`.
     *
     */
    400: ProblemDetails;
    /**
     * Missing or invalid API key. Both `xtkt_live_` (production) and `xtkt_test_`
     * (sandbox) prefixes are accepted, but the key must also be valid and active.
     *
     */
    401: ProblemDetails;
    /**
     * Billing quota exhausted. `detail` carries the reason and, where one applies, an upgrade URL.
     */
    402: ProblemDetails;
    /**
     * The key is valid but lacks the scope this endpoint requires —
     * `portal.forms.read` to read, `portal.magiclinks.write` to create. The missing
     * scope is named in the response.
     *
     */
    403: ProblemDetails;
    /**
     * No such form, or it belongs to another tenant. The two are indistinguishable by design.
     */
    404: ProblemDetails;
    /**
     * The request conflicts with the current state of what it acts on.
     */
    409: ProblemDetails;
    /**
     * Over 50 requests in the current 1-minute window for this key.
     */
    429: ProblemDetails;
    /**
     * Unexpected failure. `correlationId` identifies the request — quote it when
     * you contact support.
     *
     */
    500: ProblemDetails;
    /**
     * The Portal service is unreachable. Marked retryable — back off and try again.
     */
    502: ProblemDetails;
};

export type CreatePortalMagicLinkError = CreatePortalMagicLinkErrors[keyof CreatePortalMagicLinkErrors];

export type CreatePortalMagicLinkResponses = {
    /**
     * The link was created.
     */
    201: PortalMagicLink;
};

export type CreatePortalMagicLinkResponse = CreatePortalMagicLinkResponses[keyof CreatePortalMagicLinkResponses];
