// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://api-us.cogneris.ai' | 'https://api-eu.cogneris.ai' | (string & {});
};

export type Envelope = {
    data?: {
        id?: string;
        /**
         * Operation-specific payload, shaped by the template or operation that ran.
         * The keys are your template's, so the object itself is left open here.
         *
         * Extraction and zero-shot fill it with one entry per extracted field, and
         * each entry is an `ExtractedField`: the value, how certain the model is of
         * it, and — when the value was visually located on the page — where it was
         * read from. A table-shaped field carries an `items` array instead, whose
         * rows hold `ExtractedField` cells under the same keys.
         *
         * Source coordinates follow one convention, the same on every engine:
         *
         * - `page` is 1-indexed, and never past the document's last page.
         * - `bbox` is `[x0, y0, x1, y1]` as fractions of the page size with the
         * origin at the top-left, so `x0,y0` is the top-left corner and `x1,y1`
         * the bottom-right. Values are clamped into `0`–`1` and the corners are
         * ordered, so `x0 <= x1` and `y0 <= y1` always hold.
         * - `page`, `bbox` and `bbox_confidence` are omitted **together** for any
         * value the model could not locate on the page — a computed total, for
         * instance. Their absence is not an error, and a field object carrying
         * none of the three is ordinary.
         *
         * Every confidence this API returns is a number from `0` to `100`,
         * `bbox_confidence` included. There is no second scale to convert from.
         *
         * A document job's stored `result.json` holds the same field entries,
         * sanitized the same way, so the asynchronous answer agrees with the
         * synchronous one for the same document. It wraps them differently — see
         * `outputReference`.
         *
         */
        metadata?: {
            [key: string]: unknown;
        };
        createdDate?: string;
    };
    meta?: ServiceResponseMeta;
    hasErrors?: boolean;
};

/**
 * One extracted field: the value, how certain the model is of it, and where on the
 * document it was read from. These are the objects that fill `data.metadata`, and
 * the cells inside a table-shaped field's `items` rows.
 *
 * The three location keys are present or absent together — see `data.metadata` for
 * the coordinate convention they follow.
 *
 */
export type ExtractedField = {
    /**
     * The extracted value, or `null` when the field was not found.
     */
    value?: string | null;
    /**
     * Certainty in the value, from `0` to `100`. This is the one confidence scale
     * the API uses; `bbox_confidence` is on the same one.
     *
     */
    confidence?: number;
    /**
     * 1-indexed page the value was read from. Absent when the value could not be
     * located on the page.
     *
     */
    page?: number;
    bbox?: BoundingBox;
    /**
     * Certainty in the location, from `0` to `100` — the same scale as `confidence`,
     * not a `0`–`1` fraction. Absent whenever `bbox` is.
     *
     */
    bbox_confidence?: number;
};

/**
 * Where a value sits on its page, as `[x0, y0, x1, y1]` fractions of the page size
 * with the origin at the top-left: `x0,y0` is the top-left corner and `x1,y1` the
 * bottom-right. Fractions rather than pixels, so the box survives any rendering
 * scale — multiply by the width and height you draw the page at.
 *
 */
export type BoundingBox = [
    number,
    number,
    number,
    number
];

export type DocumentJobOperation = 'Extraction' | 'Classification' | 'ZeroShot' | 'Crop' | 'Split' | 'Redaction' | 'Facematch';

export type DocumentJobSubmitOperation = 'Extraction' | 'Classification' | 'ZeroShot' | 'Crop' | 'Split' | 'Facematch';

export type DocumentJobStatus = 'Queued' | 'Processing' | 'Succeeded' | 'Failed' | 'Cancelled';

export type DocumentJobSubmitStatus = 'Queued';

export type ServiceResponseMeta = {
    httpStatusCode: number;
    messages?: Array<string>;
    errors?: Array<ApiError>;
    creditsConsumed?: number | null;
};

export type ApiError = {
    code: string;
    message: string;
    field?: string | null;
    retryable: boolean;
    details?: {
        [key: string]: string;
    } | null;
};

export type Artifact = {
    /**
     * Pass this as a job's `inputReference`. Reusable until it expires — treat
     * it as opaque rather than parsing it.
     *
     */
    reference: string;
    /**
     * The stored name. Characters outside `A-Z a-z 0-9 . _ -` are replaced and
     * long names are truncated, so this can differ from what you sent. The
     * extension is always preserved.
     *
     */
    fileName: string;
    /**
     * The type the bytes were stored under. A non-image document is normalized
     * to `application/pdf` before storage, so this can differ from what you
     * uploaded.
     *
     */
    contentType: string;
    /**
     * Size of the stored document, which is not the size you sent when it was normalized.
     */
    sizeBytes: number;
    /**
     * When the reference stops resolving — 7 days from upload. Reads after this
     * answer `410`.
     *
     */
    expiresAt: string;
};

export type ArtifactUploadEnvelope = {
    data: Artifact;
    meta: ServiceResponseMeta;
    hasErrors: boolean;
};

export type ServiceErrorEnvelope = {
    data: {
        [key: string]: unknown;
    } | null;
    meta: ServiceResponseMeta;
    hasErrors: boolean;
};

export type DocumentJobSubmission = {
    jobId: string;
    status: DocumentJobSubmitStatus;
    statusUrl: string;
    retryAfterSeconds: number;
};

export type DocumentJobList = {
    jobs: Array<DocumentJob>;
    nextCursor?: string | null;
    hasMore: boolean;
    limit: number;
};

export type DocumentJobCancellation = {
    jobId: string;
    cancellationRequested: boolean;
};

export type DocumentJobSubmissionEnvelope = {
    data: DocumentJobSubmission;
    meta: ServiceResponseMeta;
    hasErrors: boolean;
};

export type DocumentJobEnvelope = {
    data: DocumentJob;
    meta: ServiceResponseMeta;
    hasErrors: boolean;
};

export type DocumentJobListEnvelope = {
    data: DocumentJobList;
    meta: ServiceResponseMeta;
    hasErrors: boolean;
};

export type DocumentJobCancellationEnvelope = {
    data: DocumentJobCancellation;
    meta: ServiceResponseMeta;
    hasErrors: boolean;
};

export type DocumentJob = {
    jobId?: string;
    operation?: DocumentJobOperation;
    status?: DocumentJobStatus;
    /**
     * Where the finished result is stored, as an `artifact://` reference. Read it
     * with `GET /api/v1/artifacts/content`. Null until the job succeeds, and always
     * null for `Redaction`, which has its own download route.
     *
     * For `Extraction` and `ZeroShot` its field entries are the same
     * `ExtractedField` objects a synchronous call returns for that document — same
     * source-coordinate convention, same `0`-`100` confidence scale.
     *
     * The stored `result.json` is not the response envelope and does not repeat its
     * casing: it holds the extraction result directly, with `Metadata` where the
     * synchronous body has `data.metadata`. The field names inside are your
     * template's either way.
     *
     * Jobs that completed before 2026-09-22 carry a bucket-qualified path rather
     * than an `artifact://` reference; the download accepts both.
     *
     */
    outputReference?: string | null;
    stage?: string | null;
    processedPages?: number | null;
    totalPages?: number | null;
    attemptCount?: number;
    failureCode?: string | null;
    retryable?: boolean;
    startedAt?: string | null;
    completedAt?: string | null;
    cancellationRequestedAt?: string | null;
    expiresAt?: string;
};

export type PortalForm = {
    formId?: number;
    formName?: string;
    formDescription?: string | null;
};

export type PortalChannels = {
    channels?: Array<PortalSendChannel>;
};

export type PortalSendChannel = 'email' | 'sms' | 'whatsapp';

export type PortalMagicLinkRequest = {
    /**
     * Target form, from `GET /api/v1/portal/forms`. Must be greater than zero.
     */
    formId: number;
    /**
     * Recipient display name.
     */
    name: string;
    /**
     * Channel to deliver the link on. Omit it to create the link without
     * sending anything.
     *
     */
    sendChannel?: PortalSendChannel | null;
    /**
     * Required when `sendChannel` is `email`.
     */
    email?: string | null;
    /**
     * Required when `sendChannel` is `sms` or `whatsapp`.
     */
    phone?: string | null;
    /**
     * Recipient tax id.
     */
    taxId?: string | null;
    /**
     * Days until the link expires. A value of zero or less is treated as 30.
     */
    dueDays?: number;
    /**
     * How many times the link may be opened. Null means unlimited; 1 makes it single-use.
     */
    maxAccesses?: number | null;
    /**
     * Internal note kept against the link, never shown to the recipient.
     */
    notes?: string | null;
    /**
     * WhatsApp consent for this recipient, recorded alongside creation. Supply it
     * when consent is not already on file. Omit it when consent is already held.
     * Only WhatsApp records this consent; email and SMS use their own consent rules.
     * When supplied, source and non-blank evidenceText are required for every channel.
     *
     */
    optIn?: PortalMagicLinkOptIn | null;
};

/**
 * A declaration that the recipient agreed to be messaged on WhatsApp.
 */
export type PortalMagicLinkOptIn = {
    /**
     * How the recipient's consent was collected.
     */
    source: 'web_form' | 'contract' | 'in_person' | 'import' | 'api';
    /**
     * Required, non-blank pointer to the proof of consent, such as a contract number, form id or ticket.
     */
    evidenceText: string;
    /**
     * Optional link to the evidence.
     */
    evidenceUrl?: string | null;
    /**
     * When the recipient consented. Defaults to now; supply the original date for older consent. Dates more than one day in the future are rejected.
     */
    collectedWhen?: string | null;
};

export type PortalMagicLink = {
    /**
     * The created magic link.
     */
    id?: number;
    /**
     * The link the recipient opens. Present only on the first create — the token
     * is a one-time secret that is never stored in readable form, so an
     * idempotent replay omits this field.
     *
     */
    url?: string | null;
    /**
     * Whether Cogneris dispatched the link. False when `sendChannel` was omitted or the send was suppressed.
     */
    sent?: boolean;
    /**
     * The channel actually used, when one was.
     */
    sendChannel?: PortalSendChannel | null;
    /**
     * Why delivery was suppressed when sent is false. Null or absent when delivery
     * succeeded or no send was requested. This is an open string; handle unknown values.
     * whatsapp_no_optin and whatsapp_optin_revoked require consent to be recorded;
     * whatsapp_blocked means the recipient asked to stop and consent cannot override it;
     * provider_error is transient and may be retried. The link exists even if sending
     * was suppressed; use the returned url when present.
     *
     */
    sendSuppressionReason?: string | null;
};

/**
 * RFC 9457 problem document, sent as `application/problem+json`.
 */
export type ProblemDetails = {
    /**
     * Opaque stable identifier for the error class.
     */
    type?: string;
    title?: string;
    status?: number;
    detail?: string | null;
    /**
     * The path that produced the error.
     */
    instance?: string;
    /**
     * Stable machine-readable error code — branch on this.
     */
    code?: string;
    /**
     * Also returned in the `x-correlation-id` header.
     */
    correlationId?: string;
    retryable?: boolean;
    errors?: Array<{
        code?: string;
        message?: string;
        /**
         * Present on validation failures.
         */
        field?: string;
        retryable?: boolean;
    }>;
};

export type SingleFile = {
    file: Blob | File;
};

export type ExtractDocumentData = {
    body: {
        /**
         * The document to extract from.
         */
        file: Blob | File;
        /**
         * Free-text instruction appended to the model prompt. Use it to ask
         * for extra fields, enforce formatting, or narrow the scope.
         *
         */
        ComplementaryPrompt?: string;
    };
    path?: never;
    query?: never;
    url: '/Document/extraction';
};

export type ExtractDocumentErrors = {
    /**
     * Missing or invalid API key. Both `xtkt_live_` (production) and `xtkt_test_`
     * (sandbox) prefixes are accepted, but the key must also be valid and active.
     *
     */
    401: unknown;
    /**
     * Over the size limit — 10 MB, or 500 MB on `/Document/split`.
     */
    413: unknown;
    /**
     * Extension outside the supported list.
     */
    415: unknown;
    /**
     * Over 50 requests in the current 1-minute window for this key.
     */
    429: unknown;
};

export type ExtractDocumentResponses = {
    /**
     * The service envelope. `data.metadata` is shaped by the template or operation
     * that ran, so its fields vary by document type. What does not vary is the shape of
     * each field inside it — see `ExtractedField` for the value, confidence and source
     * coordinates every extracted field carries.
     *
     */
    200: Envelope;
};

export type ExtractDocumentResponse = ExtractDocumentResponses[keyof ExtractDocumentResponses];

export type ClassifyDocumentsData = {
    body: {
        /**
         * One or more files to classify.
         */
        files: Array<Blob | File>;
    };
    path?: never;
    query?: never;
    url: '/Document/classifier';
};

export type ClassifyDocumentsErrors = {
    /**
     * Missing or invalid API key. Both `xtkt_live_` (production) and `xtkt_test_`
     * (sandbox) prefixes are accepted, but the key must also be valid and active.
     *
     */
    401: unknown;
    /**
     * Over the size limit — 10 MB, or 500 MB on `/Document/split`.
     */
    413: unknown;
    /**
     * Extension outside the supported list.
     */
    415: unknown;
    /**
     * Over 50 requests in the current 1-minute window for this key.
     */
    429: unknown;
};

export type ClassifyDocumentsResponses = {
    /**
     * The service envelope. `data.metadata` is shaped by the template or operation
     * that ran, so its fields vary by document type. What does not vary is the shape of
     * each field inside it — see `ExtractedField` for the value, confidence and source
     * coordinates every extracted field carries.
     *
     */
    200: Envelope;
};

export type ClassifyDocumentsResponse = ClassifyDocumentsResponses[keyof ClassifyDocumentsResponses];

export type ZeroShotDocumentData = {
    body: SingleFile;
    path?: never;
    query?: never;
    url: '/Document/zero-shot';
};

export type ZeroShotDocumentErrors = {
    /**
     * Missing or invalid API key. Both `xtkt_live_` (production) and `xtkt_test_`
     * (sandbox) prefixes are accepted, but the key must also be valid and active.
     *
     */
    401: unknown;
    /**
     * Over the size limit — 10 MB, or 500 MB on `/Document/split`.
     */
    413: unknown;
    /**
     * Extension outside the supported list.
     */
    415: unknown;
    /**
     * Over 50 requests in the current 1-minute window for this key.
     */
    429: unknown;
};

export type ZeroShotDocumentResponses = {
    /**
     * The service envelope. `data.metadata` is shaped by the template or operation
     * that ran, so its fields vary by document type. What does not vary is the shape of
     * each field inside it — see `ExtractedField` for the value, confidence and source
     * coordinates every extracted field carries.
     *
     */
    200: Envelope;
};

export type ZeroShotDocumentResponse = ZeroShotDocumentResponses[keyof ZeroShotDocumentResponses];

export type CropDocumentData = {
    body: SingleFile;
    path?: never;
    query?: never;
    url: '/Document/crop';
};

export type CropDocumentErrors = {
    /**
     * Missing or invalid API key. Both `xtkt_live_` (production) and `xtkt_test_`
     * (sandbox) prefixes are accepted, but the key must also be valid and active.
     *
     */
    401: unknown;
    /**
     * Over the size limit — 10 MB, or 500 MB on `/Document/split`.
     */
    413: unknown;
    /**
     * Extension outside the supported list.
     */
    415: unknown;
    /**
     * Over 50 requests in the current 1-minute window for this key.
     */
    429: unknown;
};

export type CropDocumentResponses = {
    /**
     * The service envelope. `data.metadata` is shaped by the template or operation
     * that ran, so its fields vary by document type. What does not vary is the shape of
     * each field inside it — see `ExtractedField` for the value, confidence and source
     * coordinates every extracted field carries.
     *
     */
    200: Envelope;
};

export type CropDocumentResponse = CropDocumentResponses[keyof CropDocumentResponses];

export type SplitDocumentData = {
    body: SingleFile;
    path?: never;
    query?: never;
    url: '/Document/split';
};

export type SplitDocumentErrors = {
    /**
     * Missing or invalid API key. Both `xtkt_live_` (production) and `xtkt_test_`
     * (sandbox) prefixes are accepted, but the key must also be valid and active.
     *
     */
    401: unknown;
    /**
     * Over the size limit — 10 MB, or 500 MB on `/Document/split`.
     */
    413: unknown;
    /**
     * Extension outside the supported list.
     */
    415: unknown;
    /**
     * Over 50 requests in the current 1-minute window for this key.
     */
    429: unknown;
};

export type SplitDocumentResponses = {
    /**
     * The service envelope. `data.metadata` is shaped by the template or operation
     * that ran, so its fields vary by document type. What does not vary is the shape of
     * each field inside it — see `ExtractedField` for the value, confidence and source
     * coordinates every extracted field carries.
     *
     */
    200: Envelope;
};

export type SplitDocumentResponse = SplitDocumentResponses[keyof SplitDocumentResponses];

export type FaceMatchDocumentData = {
    body: {
        /**
         * The selfie to compare.
         */
        selfie: Blob | File;
        /**
         * One or more identity documents to compare against.
         */
        documents: Array<Blob | File>;
    };
    path?: never;
    query?: never;
    url: '/Document/facematch';
};

export type FaceMatchDocumentErrors = {
    /**
     * Missing or invalid API key. Both `xtkt_live_` (production) and `xtkt_test_`
     * (sandbox) prefixes are accepted, but the key must also be valid and active.
     *
     */
    401: unknown;
    /**
     * Over the size limit — 10 MB, or 500 MB on `/Document/split`.
     */
    413: unknown;
    /**
     * Extension outside the supported list.
     */
    415: unknown;
    /**
     * Over 50 requests in the current 1-minute window for this key.
     */
    429: unknown;
};

export type FaceMatchDocumentResponses = {
    /**
     * The service envelope. `data.metadata` is shaped by the template or operation
     * that ran, so its fields vary by document type. What does not vary is the shape of
     * each field inside it — see `ExtractedField` for the value, confidence and source
     * coordinates every extracted field carries.
     *
     */
    200: Envelope;
};

export type FaceMatchDocumentResponse = FaceMatchDocumentResponses[keyof FaceMatchDocumentResponses];

export type UploadArtifactData = {
    body: {
        /**
         * The document a job will consume. Same accepted extensions and the
         * same 10 MB limit as the synchronous endpoints.
         *
         */
        file: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/api/v1/artifacts';
};

export type UploadArtifactErrors = {
    /**
     * Missing or invalid API key. Both `xtkt_live_` (production) and `xtkt_test_`
     * (sandbox) prefixes are accepted, but the key must also be valid and active.
     *
     */
    401: unknown;
    /**
     * Over the size limit — 10 MB, or 500 MB on `/Document/split`.
     */
    413: unknown;
    /**
     * Extension outside the supported list.
     */
    415: unknown;
    /**
     * The document was rejected by the security policy, or could not be
     * converted safely. The `code` says which.
     *
     */
    422: ServiceErrorEnvelope;
    /**
     * Over 50 requests in the current 1-minute window for this key.
     */
    429: unknown;
    /**
     * Document admission is temporarily unavailable. Marked retryable — back
     * off and upload again.
     *
     */
    503: ServiceErrorEnvelope;
};

export type UploadArtifactError = UploadArtifactErrors[keyof UploadArtifactErrors];

export type UploadArtifactResponses = {
    /**
     * Stored.
     */
    201: ArtifactUploadEnvelope;
};

export type UploadArtifactResponse = UploadArtifactResponses[keyof UploadArtifactResponses];

export type DownloadArtifactData = {
    body?: never;
    path?: never;
    query: {
        /**
         * An `artifact://` reference, or the bucket-qualified form an older job
         * returned. Pass back exactly what you were given.
         *
         */
        reference: string;
    };
    url: '/api/v1/artifacts/content';
};

export type DownloadArtifactErrors = {
    /**
     * The reference is missing, unreadable, or not one this tenant can read.
     * A reference belonging to another tenant answers here, not `403` — the
     * response does not reveal whether it exists.
     *
     */
    400: ServiceErrorEnvelope;
    /**
     * Missing or invalid API key. Both `xtkt_live_` (production) and `xtkt_test_`
     * (sandbox) prefixes are accepted, but the key must also be valid and active.
     *
     */
    401: unknown;
    /**
     * No artifact with that reference in this tenant.
     */
    404: unknown;
    /**
     * The reference was valid and has expired. Distinct from `404` on purpose:
     * retrying will never succeed, so upload again.
     *
     */
    410: ServiceErrorEnvelope;
    /**
     * Over 50 requests in the current 1-minute window for this key.
     */
    429: unknown;
};

export type DownloadArtifactError = DownloadArtifactErrors[keyof DownloadArtifactErrors];

export type DownloadArtifactResponses = {
    /**
     * A job result document.
     */
    200: {
        [key: string]: unknown;
    };
};

export type DownloadArtifactResponse = DownloadArtifactResponses[keyof DownloadArtifactResponses];

export type ListDocumentJobsData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
    };
    url: '/api/v1/document-jobs';
};

export type ListDocumentJobsErrors = {
    /**
     * Missing or invalid API key. Both `xtkt_live_` (production) and `xtkt_test_`
     * (sandbox) prefixes are accepted, but the key must also be valid and active.
     *
     */
    401: unknown;
    /**
     * Over 50 requests in the current 1-minute window for this key.
     */
    429: unknown;
};

export type ListDocumentJobsResponses = {
    /**
     * Jobs for the tenant.
     */
    200: DocumentJobListEnvelope;
};

export type ListDocumentJobsResponse = ListDocumentJobsResponses[keyof ListDocumentJobsResponses];

export type SubmitDocumentJobData = {
    body: {
        operation: DocumentJobSubmitOperation;
        /**
         * The `reference` returned by `POST /api/v1/artifacts`. That upload
         * is the only way to obtain one, and it can back more than one job
         * until it expires.
         *
         */
        inputReference: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/document-jobs';
};

export type SubmitDocumentJobErrors = {
    /**
     * Missing or invalid API key. Both `xtkt_live_` (production) and `xtkt_test_`
     * (sandbox) prefixes are accepted, but the key must also be valid and active.
     *
     */
    401: unknown;
    /**
     * Over 50 requests in the current 1-minute window for this key.
     */
    429: unknown;
};

export type SubmitDocumentJobResponses = {
    /**
     * Job accepted.
     */
    202: DocumentJobSubmissionEnvelope;
};

export type SubmitDocumentJobResponse = SubmitDocumentJobResponses[keyof SubmitDocumentJobResponses];

export type GetDocumentJobData = {
    body?: never;
    path: {
        jobId: string;
    };
    query?: never;
    url: '/api/v1/document-jobs/{jobId}';
};

export type GetDocumentJobErrors = {
    /**
     * Missing or invalid API key. Both `xtkt_live_` (production) and `xtkt_test_`
     * (sandbox) prefixes are accepted, but the key must also be valid and active.
     *
     */
    401: unknown;
    /**
     * No job with that id in this tenant.
     */
    404: unknown;
    /**
     * Over 50 requests in the current 1-minute window for this key.
     */
    429: unknown;
};

export type GetDocumentJobResponses = {
    /**
     * The job.
     */
    200: DocumentJobEnvelope;
};

export type GetDocumentJobResponse = GetDocumentJobResponses[keyof GetDocumentJobResponses];

export type CancelDocumentJobData = {
    body?: never;
    path: {
        jobId: string;
    };
    query?: never;
    url: '/api/v1/document-jobs/{jobId}/cancel';
};

export type CancelDocumentJobErrors = {
    /**
     * Missing or invalid API key. Both `xtkt_live_` (production) and `xtkt_test_`
     * (sandbox) prefixes are accepted, but the key must also be valid and active.
     *
     */
    401: unknown;
    /**
     * The job does not exist or can no longer be cancelled.
     */
    409: ServiceErrorEnvelope;
    /**
     * Over 50 requests in the current 1-minute window for this key.
     */
    429: unknown;
};

export type CancelDocumentJobError = CancelDocumentJobErrors[keyof CancelDocumentJobErrors];

export type CancelDocumentJobResponses = {
    /**
     * Cancellation requested.
     */
    202: DocumentJobCancellationEnvelope;
};

export type CancelDocumentJobResponse = CancelDocumentJobResponses[keyof CancelDocumentJobResponses];

export type ListPortalFormsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/portal/forms';
};

export type ListPortalFormsErrors = {
    /**
     * Missing or invalid API key. Both `xtkt_live_` (production) and `xtkt_test_`
     * (sandbox) prefixes are accepted, but the key must also be valid and active.
     *
     */
    401: unknown;
    /**
     * The key is valid but lacks the scope this endpoint requires —
     * `portal.forms.read` to read, `portal.magiclinks.write` to create. The missing
     * scope is named in the response.
     *
     */
    403: ProblemDetails;
    /**
     * Over 50 requests in the current 1-minute window for this key.
     */
    429: unknown;
    /**
     * The Portal service is unreachable. Marked retryable — back off and try again.
     */
    502: ProblemDetails;
};

export type ListPortalFormsError = ListPortalFormsErrors[keyof ListPortalFormsErrors];

export type ListPortalFormsResponses = {
    /**
     * The tenant's forms.
     */
    200: Array<PortalForm>;
};

export type ListPortalFormsResponse = ListPortalFormsResponses[keyof ListPortalFormsResponses];

export type ListPortalChannelsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/portal/available-channels';
};

export type ListPortalChannelsErrors = {
    /**
     * Missing or invalid API key. Both `xtkt_live_` (production) and `xtkt_test_`
     * (sandbox) prefixes are accepted, but the key must also be valid and active.
     *
     */
    401: unknown;
    /**
     * The key is valid but lacks the scope this endpoint requires —
     * `portal.forms.read` to read, `portal.magiclinks.write` to create. The missing
     * scope is named in the response.
     *
     */
    403: ProblemDetails;
    /**
     * Over 50 requests in the current 1-minute window for this key.
     */
    429: unknown;
    /**
     * The Portal service is unreachable. Marked retryable — back off and try again.
     */
    502: ProblemDetails;
};

export type ListPortalChannelsError = ListPortalChannelsErrors[keyof ListPortalChannelsErrors];

export type ListPortalChannelsResponses = {
    /**
     * The enabled channels.
     */
    200: PortalChannels;
};

export type ListPortalChannelsResponse = ListPortalChannelsResponses[keyof ListPortalChannelsResponses];

export type CreatePortalMagicLinkData = {
    body: PortalMagicLinkRequest;
    headers?: {
        /**
         * Stable caller-supplied key that makes a retry resolve to the same link.
         */
        'Idempotency-Key'?: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/portal/magic-link';
};

export type CreatePortalMagicLinkErrors = {
    /**
     * A field failed validation — a missing `formId` or `name`, a `sendChannel`
     * outside the allowed set, or a channel whose matching contact field is absent.
     * The offending field is named in `errors[].field`.
     *
     */
    400: unknown;
    /**
     * Missing or invalid API key. Both `xtkt_live_` (production) and `xtkt_test_`
     * (sandbox) prefixes are accepted, but the key must also be valid and active.
     *
     */
    401: unknown;
    /**
     * Billing quota exhausted. `detail` carries the reason and, where one applies, an upgrade URL.
     */
    402: unknown;
    /**
     * The key is valid but lacks the scope this endpoint requires —
     * `portal.forms.read` to read, `portal.magiclinks.write` to create. The missing
     * scope is named in the response.
     *
     */
    403: ProblemDetails;
    /**
     * No such form, or it belongs to another tenant. The two are indistinguishable by design.
     */
    404: unknown;
    /**
     * Over 50 requests in the current 1-minute window for this key.
     */
    429: unknown;
    /**
     * The Portal service is unreachable. Marked retryable — back off and try again.
     */
    502: ProblemDetails;
};

export type CreatePortalMagicLinkError = CreatePortalMagicLinkErrors[keyof CreatePortalMagicLinkErrors];

export type CreatePortalMagicLinkResponses = {
    /**
     * The link was created.
     */
    201: PortalMagicLink;
};

export type CreatePortalMagicLinkResponse = CreatePortalMagicLinkResponses[keyof CreatePortalMagicLinkResponses];
