// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://api-us.cogneris.ai' | 'https://api-eu.cogneris.ai' | (string & {});
};

export type Envelope = {
    data?: {
        id?: string;
        /**
         * Operation-specific payload.
         */
        metadata?: {
            [key: string]: unknown;
        };
        createdDate?: string;
    };
    meta?: {
        httpStatusCode?: number;
        messages?: Array<string>;
    };
    hasErrors?: boolean;
};

export type DocumentJobOperation = 'Extraction' | 'Classification' | 'ZeroShot' | 'Crop' | 'Split';

export type DocumentJobStatus = 'Queued' | 'Processing' | 'Succeeded' | 'Failed' | 'Cancelled';

export type DocumentJob = {
    jobId?: string;
    operation?: DocumentJobOperation;
    status?: DocumentJobStatus;
    outputReference?: string | null;
    attemptCount?: number;
    failureCode?: string | null;
    retryable?: boolean;
    startedAt?: string | null;
    completedAt?: string | null;
    cancellationRequestedAt?: string | null;
    expiresAt?: string;
};

export type PortalForm = {
    formId?: number;
    formName?: string;
    formDescription?: string | null;
};

export type PortalChannels = {
    channels?: Array<PortalSendChannel>;
};

export type PortalSendChannel = 'email' | 'sms' | 'whatsapp';

export type PortalMagicLinkRequest = {
    /**
     * Target form, from `GET /api/v1/portal/forms`. Must be greater than zero.
     */
    formId: number;
    /**
     * Recipient display name.
     */
    name: string;
    /**
     * Channel to deliver the link on. Omit it to create the link without
     * sending anything.
     *
     */
    sendChannel?: PortalSendChannel | null;
    /**
     * Required when `sendChannel` is `email`.
     */
    email?: string | null;
    /**
     * Required when `sendChannel` is `sms` or `whatsapp`.
     */
    phone?: string | null;
    /**
     * Recipient tax id.
     */
    taxId?: string | null;
    /**
     * Days until the link expires. A value of zero or less is treated as 30.
     */
    dueDays?: number;
    /**
     * How many times the link may be opened. Null means unlimited; 1 makes it single-use.
     */
    maxAccesses?: number | null;
    /**
     * Internal note kept against the link, never shown to the recipient.
     */
    notes?: string | null;
};

export type PortalMagicLink = {
    /**
     * The created magic link.
     */
    id?: number;
    /**
     * The link the recipient opens. Present only on the first create — the token
     * is a one-time secret that is never stored in readable form, so an
     * idempotent replay omits this field.
     *
     */
    url?: string | null;
    /**
     * Whether Cogneris dispatched the link. False when `sendChannel` was omitted or the send was suppressed.
     */
    sent?: boolean;
    /**
     * The channel actually used, when one was.
     */
    sendChannel?: PortalSendChannel | null;
};

/**
 * RFC 9457 problem document, sent as `application/problem+json`.
 */
export type ProblemDetails = {
    /**
     * Opaque stable identifier for the error class.
     */
    type?: string;
    title?: string;
    status?: number;
    detail?: string | null;
    /**
     * The path that produced the error.
     */
    instance?: string;
    /**
     * Stable machine-readable error code — branch on this.
     */
    code?: string;
    /**
     * Also returned in the `x-correlation-id` header.
     */
    correlationId?: string;
    retryable?: boolean;
    errors?: Array<{
        code?: string;
        message?: string;
        /**
         * Present on validation failures.
         */
        field?: string;
        retryable?: boolean;
    }>;
};

export type SingleFile = {
    file: Blob | File;
};

export type ExtractDocumentData = {
    body: {
        /**
         * The document to extract from.
         */
        file: Blob | File;
        /**
         * Free-text instruction appended to the model prompt. Use it to ask
         * for extra fields, enforce formatting, or narrow the scope.
         *
         */
        ComplementaryPrompt?: string;
    };
    path?: never;
    query?: never;
    url: '/Document/extraction';
};

export type ExtractDocumentErrors = {
    /**
     * Missing key, or one that does not begin with `xtkt_live_`.
     */
    401: unknown;
    /**
     * Over the size limit — 10 MB, or 500 MB on `/Document/split`.
     */
    413: unknown;
    /**
     * Extension outside the supported list.
     */
    415: unknown;
    /**
     * Over 50 requests in the current 1-minute window for this key.
     */
    429: unknown;
};

export type ExtractDocumentResponses = {
    /**
     * The service envelope. `data.metadata` is shaped by the template or operation
     * that ran, so its fields vary by document type.
     *
     */
    200: Envelope;
};

export type ExtractDocumentResponse = ExtractDocumentResponses[keyof ExtractDocumentResponses];

export type ClassifyDocumentsData = {
    body: {
        /**
         * One or more files to classify.
         */
        files: Array<Blob | File>;
    };
    path?: never;
    query?: never;
    url: '/Document/classifier';
};

export type ClassifyDocumentsErrors = {
    /**
     * Missing key, or one that does not begin with `xtkt_live_`.
     */
    401: unknown;
    /**
     * Over the size limit — 10 MB, or 500 MB on `/Document/split`.
     */
    413: unknown;
    /**
     * Extension outside the supported list.
     */
    415: unknown;
    /**
     * Over 50 requests in the current 1-minute window for this key.
     */
    429: unknown;
};

export type ClassifyDocumentsResponses = {
    /**
     * The service envelope. `data.metadata` is shaped by the template or operation
     * that ran, so its fields vary by document type.
     *
     */
    200: Envelope;
};

export type ClassifyDocumentsResponse = ClassifyDocumentsResponses[keyof ClassifyDocumentsResponses];

export type ZeroShotDocumentData = {
    body: SingleFile;
    path?: never;
    query?: never;
    url: '/Document/zero-shot';
};

export type ZeroShotDocumentErrors = {
    /**
     * Missing key, or one that does not begin with `xtkt_live_`.
     */
    401: unknown;
    /**
     * Over the size limit — 10 MB, or 500 MB on `/Document/split`.
     */
    413: unknown;
    /**
     * Extension outside the supported list.
     */
    415: unknown;
    /**
     * Over 50 requests in the current 1-minute window for this key.
     */
    429: unknown;
};

export type ZeroShotDocumentResponses = {
    /**
     * The service envelope. `data.metadata` is shaped by the template or operation
     * that ran, so its fields vary by document type.
     *
     */
    200: Envelope;
};

export type ZeroShotDocumentResponse = ZeroShotDocumentResponses[keyof ZeroShotDocumentResponses];

export type CropDocumentData = {
    body: SingleFile;
    path?: never;
    query?: never;
    url: '/Document/crop';
};

export type CropDocumentErrors = {
    /**
     * Missing key, or one that does not begin with `xtkt_live_`.
     */
    401: unknown;
    /**
     * Over the size limit — 10 MB, or 500 MB on `/Document/split`.
     */
    413: unknown;
    /**
     * Extension outside the supported list.
     */
    415: unknown;
    /**
     * Over 50 requests in the current 1-minute window for this key.
     */
    429: unknown;
};

export type CropDocumentResponses = {
    /**
     * The service envelope. `data.metadata` is shaped by the template or operation
     * that ran, so its fields vary by document type.
     *
     */
    200: Envelope;
};

export type CropDocumentResponse = CropDocumentResponses[keyof CropDocumentResponses];

export type SplitDocumentData = {
    body: SingleFile;
    path?: never;
    query?: never;
    url: '/Document/split';
};

export type SplitDocumentErrors = {
    /**
     * Missing key, or one that does not begin with `xtkt_live_`.
     */
    401: unknown;
    /**
     * Over the size limit — 10 MB, or 500 MB on `/Document/split`.
     */
    413: unknown;
    /**
     * Extension outside the supported list.
     */
    415: unknown;
    /**
     * Over 50 requests in the current 1-minute window for this key.
     */
    429: unknown;
};

export type SplitDocumentResponses = {
    /**
     * The service envelope. `data.metadata` is shaped by the template or operation
     * that ran, so its fields vary by document type.
     *
     */
    200: Envelope;
};

export type SplitDocumentResponse = SplitDocumentResponses[keyof SplitDocumentResponses];

export type FaceMatchDocumentData = {
    body: {
        /**
         * The selfie to compare.
         */
        selfie: Blob | File;
        /**
         * One or more identity documents to compare against.
         */
        documents: Array<Blob | File>;
    };
    path?: never;
    query?: never;
    url: '/Document/facematch';
};

export type FaceMatchDocumentErrors = {
    /**
     * Missing key, or one that does not begin with `xtkt_live_`.
     */
    401: unknown;
    /**
     * Over the size limit — 10 MB, or 500 MB on `/Document/split`.
     */
    413: unknown;
    /**
     * Extension outside the supported list.
     */
    415: unknown;
    /**
     * Over 50 requests in the current 1-minute window for this key.
     */
    429: unknown;
};

export type FaceMatchDocumentResponses = {
    /**
     * The service envelope. `data.metadata` is shaped by the template or operation
     * that ran, so its fields vary by document type.
     *
     */
    200: Envelope;
};

export type FaceMatchDocumentResponse = FaceMatchDocumentResponses[keyof FaceMatchDocumentResponses];

export type ListDocumentJobsData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
    };
    url: '/api/v1/document-jobs';
};

export type ListDocumentJobsErrors = {
    /**
     * Missing key, or one that does not begin with `xtkt_live_`.
     */
    401: unknown;
    /**
     * Over 50 requests in the current 1-minute window for this key.
     */
    429: unknown;
};

export type ListDocumentJobsResponses = {
    /**
     * Jobs for the tenant.
     */
    200: {
        jobs?: Array<DocumentJob>;
    };
};

export type ListDocumentJobsResponse = ListDocumentJobsResponses[keyof ListDocumentJobsResponses];

export type SubmitDocumentJobData = {
    body: {
        operation: DocumentJobOperation;
        /**
         * Reference to the already-uploaded input.
         */
        inputReference: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/document-jobs';
};

export type SubmitDocumentJobErrors = {
    /**
     * Missing key, or one that does not begin with `xtkt_live_`.
     */
    401: unknown;
    /**
     * Over 50 requests in the current 1-minute window for this key.
     */
    429: unknown;
};

export type SubmitDocumentJobResponses = {
    /**
     * Job accepted.
     */
    202: {
        jobId?: string;
        status?: DocumentJobStatus;
        statusUrl?: string;
        retryAfterSeconds?: number;
    };
};

export type SubmitDocumentJobResponse = SubmitDocumentJobResponses[keyof SubmitDocumentJobResponses];

export type GetDocumentJobData = {
    body?: never;
    path: {
        jobId: string;
    };
    query?: never;
    url: '/api/v1/document-jobs/{jobId}';
};

export type GetDocumentJobErrors = {
    /**
     * Missing key, or one that does not begin with `xtkt_live_`.
     */
    401: unknown;
    /**
     * No job with that id in this tenant.
     */
    404: unknown;
    /**
     * Over 50 requests in the current 1-minute window for this key.
     */
    429: unknown;
};

export type GetDocumentJobResponses = {
    /**
     * The job.
     */
    200: DocumentJob;
};

export type GetDocumentJobResponse = GetDocumentJobResponses[keyof GetDocumentJobResponses];

export type CancelDocumentJobData = {
    body?: never;
    path: {
        jobId: string;
    };
    query?: never;
    url: '/api/v1/document-jobs/{jobId}/cancel';
};

export type CancelDocumentJobErrors = {
    /**
     * Missing key, or one that does not begin with `xtkt_live_`.
     */
    401: unknown;
    /**
     * No job with that id in this tenant.
     */
    404: unknown;
    /**
     * Over 50 requests in the current 1-minute window for this key.
     */
    429: unknown;
};

export type CancelDocumentJobResponses = {
    /**
     * Cancellation requested.
     */
    200: DocumentJob;
};

export type CancelDocumentJobResponse = CancelDocumentJobResponses[keyof CancelDocumentJobResponses];

export type ListPortalFormsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/portal/forms';
};

export type ListPortalFormsErrors = {
    /**
     * Missing key, or one that does not begin with `xtkt_live_`.
     */
    401: unknown;
    /**
     * The key is valid but lacks the scope this endpoint requires —
     * `portal.forms.read` to read, `portal.magiclinks.write` to create. The missing
     * scope is named in the response.
     *
     */
    403: ProblemDetails;
    /**
     * Over 50 requests in the current 1-minute window for this key.
     */
    429: unknown;
    /**
     * The Portal service is unreachable. Marked retryable — back off and try again.
     */
    502: ProblemDetails;
};

export type ListPortalFormsError = ListPortalFormsErrors[keyof ListPortalFormsErrors];

export type ListPortalFormsResponses = {
    /**
     * The tenant's forms.
     */
    200: Array<PortalForm>;
};

export type ListPortalFormsResponse = ListPortalFormsResponses[keyof ListPortalFormsResponses];

export type ListPortalChannelsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/portal/available-channels';
};

export type ListPortalChannelsErrors = {
    /**
     * Missing key, or one that does not begin with `xtkt_live_`.
     */
    401: unknown;
    /**
     * The key is valid but lacks the scope this endpoint requires —
     * `portal.forms.read` to read, `portal.magiclinks.write` to create. The missing
     * scope is named in the response.
     *
     */
    403: ProblemDetails;
    /**
     * Over 50 requests in the current 1-minute window for this key.
     */
    429: unknown;
    /**
     * The Portal service is unreachable. Marked retryable — back off and try again.
     */
    502: ProblemDetails;
};

export type ListPortalChannelsError = ListPortalChannelsErrors[keyof ListPortalChannelsErrors];

export type ListPortalChannelsResponses = {
    /**
     * The enabled channels.
     */
    200: PortalChannels;
};

export type ListPortalChannelsResponse = ListPortalChannelsResponses[keyof ListPortalChannelsResponses];

export type CreatePortalMagicLinkData = {
    body: PortalMagicLinkRequest;
    headers?: {
        /**
         * Stable caller-supplied key that makes a retry resolve to the same link.
         */
        'Idempotency-Key'?: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/portal/magic-link';
};

export type CreatePortalMagicLinkErrors = {
    /**
     * A field failed validation — a missing `formId` or `name`, a `sendChannel`
     * outside the allowed set, or a channel whose matching contact field is absent.
     * The offending field is named in `errors[].field`.
     *
     */
    400: unknown;
    /**
     * Missing key, or one that does not begin with `xtkt_live_`.
     */
    401: unknown;
    /**
     * Billing quota exhausted. `detail` carries the reason and, where one applies, an upgrade URL.
     */
    402: unknown;
    /**
     * The key is valid but lacks the scope this endpoint requires —
     * `portal.forms.read` to read, `portal.magiclinks.write` to create. The missing
     * scope is named in the response.
     *
     */
    403: ProblemDetails;
    /**
     * No such form
     */
    404: unknown;
    /**
     * Over 50 requests in the current 1-minute window for this key.
     */
    429: unknown;
    /**
     * The Portal service is unreachable. Marked retryable — back off and try again.
     */
    502: ProblemDetails;
};

export type CreatePortalMagicLinkError = CreatePortalMagicLinkErrors[keyof CreatePortalMagicLinkErrors];

export type CreatePortalMagicLinkResponses = {
    /**
     * The link was created.
     */
    201: PortalMagicLink;
};

export type CreatePortalMagicLinkResponse = CreatePortalMagicLinkResponses[keyof CreatePortalMagicLinkResponses];
